version = 1

test_patterns = [
  "**/*_test.go",
  "frontend/**/*.test.ts",
  "frontend/**/*.test.tsx",
  "frontend/**/*.spec.ts",
  "frontend/**/*.spec.tsx"
]

exclude_patterns = [
  "vendor/**",
  "**/node_modules/**",
  "frontend/coverage/**",
  "backend/migrations/**",
  "backend/bin/**"
]

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_root = "github.com/imrishuroy/algopatterns"

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = ["nodejs"]
dialect = "typescript"
plugins = ["react"]

[[analyzers.issue_omission]]
issue_code = "JS-0067"

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers.issue_omission]]
issue_code = "SCT-A000"
