-- Quiz Questions for Go OOP Part 3: SOLID Principles
-- Sections: solid-intro, srp-ocp, lsp-isp, dip-di

-- SOLID Intro
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'solid-intro';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'solid-intro', 'multiple-choice', 'easy', 'What does SOLID stand for?', NULL, '["Five design principles for maintainable code", "A Go-specific coding standard", "A testing methodology", "A performance optimization technique"]', '0', 'SOLID is five OOP principles: Single Responsibility, Open-Closed, Liskov Substitution, Interface Segregation, Dependency Inversion.', 1),
('go-oop', 'solid-intro', 'multiple-choice', 'easy', 'Which principle says a class should have one reason to change?', NULL, '["Open-Closed", "Single Responsibility", "Liskov Substitution", "Dependency Inversion"]', '1', 'Single Responsibility Principle (SRP): a type should have only one reason to change, one job.', 2),
('go-oop', 'solid-intro', 'true-false', 'medium', 'SOLID principles were designed specifically for Go.', NULL, NULL, 'false', 'SOLID was created for OOP languages. Go adapts these principles to its composition-based model.', 3),
('go-oop', 'solid-intro', 'multiple-choice', 'medium', 'How does Go naturally support Interface Segregation?', NULL, '["Through inheritance", "By encouraging small, focused interfaces", "Through generics", "By requiring explicit implements"]', '1', 'Go idiom favors small interfaces (io.Reader has 1 method). This naturally aligns with ISP.', 4),
('go-oop', 'solid-intro', 'code-output', 'medium', 'Which SOLID principle does this violate?', 'type UserService struct{}\nfunc (s *UserService) CreateUser(u User) error { }\nfunc (s *UserService) SendEmail(to, msg string) error { }\nfunc (s *UserService) GenerateReport() []byte { }', '["None", "Single Responsibility - does too many things", "Open-Closed", "Liskov Substitution"]', '1', 'UserService handles users, emails, AND reports. Each is a different reason to change, violating SRP.', 5),
('go-oop', 'solid-intro', 'multiple-choice', 'medium', 'What does Open-Closed mean?', NULL, '["Open source code", "Open for extension, closed for modification", "Open files must be closed", "Open APIs only"]', '1', 'OCP: software should be open for extension (add new behavior) but closed for modification (don''t change existing code).', 6),
('go-oop', 'solid-intro', 'true-false', 'easy', 'Go interfaces help achieve Dependency Inversion.', NULL, NULL, 'true', 'Interfaces allow high-level modules to depend on abstractions, not concrete implementations.', 7),
('go-oop', 'solid-intro', 'multiple-choice', 'hard', 'When might you intentionally violate SOLID?', NULL, '["Never", "For simple scripts or prototypes where overhead outweighs benefits", "When using generics", "When writing tests"]', '1', 'SOLID adds complexity. For small programs, scripts, or prototypes, simpler code may be better.', 8),
('go-oop', 'solid-intro', 'code-output', 'medium', 'Which principle does this follow?', 'type Notifier interface {\n    Notify(msg string) error\n}\n\ntype EmailNotifier struct{}\ntype SMSNotifier struct{}\ntype SlackNotifier struct{}', '["SRP - each notifier does one thing", "OCP - new notifiers don''t change existing code", "Both SRP and OCP", "Neither"]', '2', 'Each notifier has one job (SRP). Adding new notifiers doesn''t modify existing ones (OCP).', 9),
('go-oop', 'solid-intro', 'multiple-choice', 'medium', 'What is the main benefit of following SOLID?', NULL, '["Faster code execution", "Easier to test, maintain, and extend code", "Smaller binary size", "Fewer lines of code"]', '1', 'SOLID produces code that is easier to test (mockable), maintain (isolated changes), and extend (add features).', 10),
('go-oop', 'solid-intro', 'identify-bug', 'hard', 'What SOLID principle does this violate?', 'func ProcessPayment(p Payment) error {\n    if p.Type == "credit" {\n        // credit card logic\n    } else if p.Type == "paypal" {\n        // paypal logic\n    } else if p.Type == "crypto" {\n        // crypto logic\n    }\n}', '["SRP", "OCP - adding payment types requires modifying this function", "LSP", "DIP"]', '1', 'Adding new payment types requires modifying ProcessPayment. Use interface + implementations instead.', 11),
('go-oop', 'solid-intro', 'true-false', 'medium', 'LSP states that derived types must be substitutable for their base types.', NULL, NULL, 'true', 'Liskov Substitution: if S is a subtype of T, objects of T can be replaced with S without breaking the program.', 12),
('go-oop', 'solid-intro', 'multiple-choice', 'easy', 'What is Dependency Inversion about?', NULL, '["Inverting control flow", "High-level modules should not depend on low-level modules; both depend on abstractions", "Reversing dependencies at runtime", "Using dependency injection frameworks"]', '1', 'DIP: depend on abstractions (interfaces), not concrete implementations. This decouples modules.', 13),
('go-oop', 'solid-intro', 'code-output', 'hard', 'How does Go''s implicit interface implementation help SOLID?', NULL, '["It doesn''t help", "Types satisfy interfaces without coupling to them, enabling DIP naturally", "It makes SRP easier", "It enforces OCP"]', '1', 'Implicit implementation means types don''t import interfaces they implement, reducing coupling (DIP).', 14),
('go-oop', 'solid-intro', 'multiple-choice', 'medium', 'What is the relationship between SOLID and Go''s "Accept interfaces, return structs"?', NULL, '["No relationship", "This idiom implements DIP - depend on abstractions (interfaces)", "This violates OCP", "This is SRP"]', '1', 'Accepting interfaces means depending on abstractions, not concrete types - this is Dependency Inversion.', 15);

-- SRP and OCP
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'srp-ocp';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'srp-ocp', 'multiple-choice', 'easy', 'What is a "reason to change" in SRP?', NULL, '["A bug fix", "A change in business requirements for one aspect", "Any code modification", "A performance improvement"]', '1', 'A "reason to change" is a change in requirements for one responsibility. User validation vs. user persistence are different reasons.', 1),
('go-oop', 'srp-ocp', 'code-output', 'medium', 'How many responsibilities does this have?', 'type OrderProcessor struct{}\nfunc (p *OrderProcessor) ValidateOrder(o Order) error { }\nfunc (p *OrderProcessor) CalculateTax(o Order) float64 { }\nfunc (p *OrderProcessor) SaveToDatabase(o Order) error { }\nfunc (p *OrderProcessor) SendConfirmationEmail(o Order) error { }', '["1", "2", "4", "Cannot determine"]', '2', 'Four responsibilities: validation, tax calculation, persistence, notification. Each could change independently.', 2),
('go-oop', 'srp-ocp', 'identify-bug', 'medium', 'What is the SRP violation?', 'type Logger struct {\n    file *os.File\n}\nfunc (l *Logger) Log(msg string) { l.file.WriteString(msg) }\nfunc (l *Logger) Rotate() error { /* rotate log files */ }\nfunc (l *Logger) Compress() error { /* compress old logs */ }', '["No violation", "Logger handles writing AND file management", "Should use interface", "Missing error handling"]', '1', 'Logger mixes logging (writing) with file management (rotation, compression). Split into Logger and LogFileManager.', 3),
('go-oop', 'srp-ocp', 'true-false', 'easy', 'In Go, packages should also follow SRP.', NULL, NULL, 'true', 'SRP applies to packages too. Package http handles HTTP, package json handles JSON. One clear purpose per package.', 4),
('go-oop', 'srp-ocp', 'multiple-choice', 'medium', 'How do you refactor an SRP violation?', NULL, '["Add more methods", "Split into multiple types, each with one responsibility", "Use inheritance", "Add comments"]', '1', 'Extract each responsibility into its own type. UserValidator, UserRepository, UserNotifier instead of UserService.', 5),
('go-oop', 'srp-ocp', 'code-output', 'medium', 'Is this open for extension?', 'type Formatter interface {\n    Format(data []byte) string\n}\n\ntype JSONFormatter struct{}\ntype XMLFormatter struct{}\ntype CSVFormatter struct{}', '["Yes - add new formatters without changing existing", "No - must modify interface", "Partially", "Cannot determine"]', '0', 'The interface is closed (stable). New formatters extend functionality without modifying existing code.', 6),
('go-oop', 'srp-ocp', 'multiple-choice', 'hard', 'What enables OCP in Go?', NULL, '["Inheritance", "Interfaces and composition", "Generics only", "Reflection"]', '1', 'Go achieves OCP through interfaces (define behavior) and composition (extend via embedding/delegation).', 7),
('go-oop', 'srp-ocp', 'code-output', 'hard', 'Why does this violate OCP?', 'func Export(data []byte, format string) string {\n    switch format {\n    case "json": return toJSON(data)\n    case "xml": return toXML(data)\n    case "csv": return toCSV(data)\n    }\n    return ""\n}', '["It doesn''t violate OCP", "Adding new formats requires modifying Export function", "Missing default case", "Should return error"]', '1', 'Every new format requires modifying Export. Use interface Exporter with method Export(data) string instead.', 8),
('go-oop', 'srp-ocp', 'true-false', 'medium', 'OCP means you should never modify existing code.', NULL, NULL, 'false', 'OCP means prefer extension over modification when adding features. Bug fixes and refactoring still modify code.', 9),
('go-oop', 'srp-ocp', 'multiple-choice', 'medium', 'What is the strategy pattern''s relationship to OCP?', NULL, '["No relationship", "Strategy enables OCP by encapsulating algorithms behind interfaces", "Strategy violates OCP", "Strategy is only for SRP"]', '1', 'Strategy pattern encapsulates interchangeable algorithms. New strategies extend behavior without modifying context.', 10),
('go-oop', 'srp-ocp', 'code-output', 'medium', 'How does this follow OCP?', 'type PaymentProcessor struct {\n    strategy PaymentStrategy\n}\nfunc (p *PaymentProcessor) Process(amount float64) error {\n    return p.strategy.Pay(amount)\n}', '["It doesn''t", "New payment methods don''t require changing PaymentProcessor", "Strategy must be modified", "Only works with one payment type"]', '1', 'PaymentProcessor is closed for modification. Adding new payment types means new strategy implementations, not changes here.', 11),
('go-oop', 'srp-ocp', 'identify-bug', 'hard', 'What is the design issue?', 'type Report struct {\n    data []byte\n}\nfunc (r *Report) Generate() { }\nfunc (r *Report) SaveToPDF() { }\nfunc (r *Report) SaveToExcel() { }\nfunc (r *Report) SendByEmail() { }', '["Violates SRP - Report does generation, formatting, AND sending", "Violates only OCP", "No issue", "Missing interface"]', '0', 'Report has multiple responsibilities. Split into ReportGenerator, ReportExporter, ReportSender.', 12),
('go-oop', 'srp-ocp', 'multiple-choice', 'medium', 'How do SRP and OCP relate?', NULL, '["They are opposites", "SRP makes OCP easier - focused types are easier to extend", "OCP makes SRP unnecessary", "They are independent"]', '1', 'Types with single responsibilities are easier to extend (OCP). Focused types have clear extension points.', 13),
('go-oop', 'srp-ocp', 'true-false', 'easy', 'Adding a method to an interface violates OCP if existing implementations must change.', NULL, NULL, 'true', 'If adding a method forces all implementations to change, you''re modifying existing code. Consider a new interface.', 14),
('go-oop', 'srp-ocp', 'code-output', 'hard', 'What is the SRP way to handle this?', 'type User struct {\n    // Should handle: validation, persistence, authentication, authorization\n}', '["All in User methods", "UserValidator + UserRepository + Authenticator + Authorizer", "Use inheritance", "One big interface"]', '1', 'Each concern becomes its own type/interface. User struct holds data; behaviors are handled by separate components.', 15);

-- LSP and ISP
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'lsp-isp';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'lsp-isp', 'multiple-choice', 'easy', 'What does LSP require?', NULL, '["All types must have the same methods", "Subtypes must be usable wherever their base type is expected", "Types must inherit from a base class", "Interfaces must be large"]', '1', 'LSP: if interface I is expected, any implementation of I must work correctly without surprising behavior.', 1),
('go-oop', 'lsp-isp', 'code-output', 'medium', 'Does this violate LSP?', 'type Bird interface {\n    Fly() error\n}\n\ntype Penguin struct{}\nfunc (p Penguin) Fly() error {\n    return errors.New("penguins cannot fly")\n}', '["No, it implements the interface", "Yes, Penguin cannot substitute for Bird expectation", "Depends on usage", "LSP doesn''t apply to Go"]', '1', 'Code expecting Bird.Fly() to succeed will break with Penguin. Penguin is not a valid substitute.', 2),
('go-oop', 'lsp-isp', 'multiple-choice', 'medium', 'How do you fix the Penguin/Bird LSP violation?', NULL, '["Make Penguin throw exception", "Split Bird into Flyer and Walker interfaces", "Remove Fly from Penguin", "Ignore the issue"]', '1', 'Create focused interfaces: type Flyer interface { Fly() }; type Walker interface { Walk() }. Penguin implements Walker.', 3),
('go-oop', 'lsp-isp', 'true-false', 'medium', 'In Go, LSP applies to interface implementations.', NULL, NULL, 'true', 'Any type implementing an interface must be substitutable wherever that interface is used.', 4),
('go-oop', 'lsp-isp', 'identify-bug', 'hard', 'What is the LSP violation?', 'type Repository interface {\n    Save(entity Entity) error\n    Delete(id string) error\n}\n\ntype ReadOnlyRepo struct{}\nfunc (r ReadOnlyRepo) Save(e Entity) error { return errors.New("read only") }\nfunc (r ReadOnlyRepo) Delete(id string) error { return errors.New("read only") }', '["No violation", "ReadOnlyRepo cannot substitute for Repository - always fails writes", "Missing method", "Should panic instead"]', '1', 'Code expecting Repository to save will always fail with ReadOnlyRepo. Use separate Reader and Writer interfaces.', 5),
('go-oop', 'lsp-isp', 'multiple-choice', 'easy', 'What does ISP stand for?', NULL, '["Interface Segregation Principle", "Interface Simplification Protocol", "Implementation Separation Pattern", "Internal Service Provider"]', '0', 'Interface Segregation Principle: clients should not be forced to depend on interfaces they don''t use.', 6),
('go-oop', 'lsp-isp', 'code-output', 'medium', 'Is this interface too large?', 'type DataStore interface {\n    Save(data []byte) error\n    Load(id string) ([]byte, error)\n    Delete(id string) error\n    List() ([]string, error)\n    Backup() error\n    Restore(path string) error\n    Migrate(version int) error\n}', '["No, it''s well-organized", "Yes, clients needing only Save/Load must depend on backup/migrate methods", "Size is fine", "Needs more methods"]', '1', 'A service needing only basic CRUD must still implement/mock backup, restore, migrate. Split into smaller interfaces.', 7),
('go-oop', 'lsp-isp', 'multiple-choice', 'medium', 'How do you apply ISP?', NULL, '["Make one large interface", "Split into small, focused interfaces", "Use abstract classes", "Avoid interfaces entirely"]', '1', 'ISP: create small interfaces. type Reader interface { Read() }; type Writer interface { Write() } instead of ReaderWriter.', 8),
('go-oop', 'lsp-isp', 'code-output', 'easy', 'Which is ISP-compliant?', NULL, '["type Worker interface { Work(); Eat(); Sleep(); Manage() }", "type Worker interface { Work() }; type Eater interface { Eat() }", "Both are fine", "Neither"]', '1', 'Small, focused interfaces. A robot Worker doesn''t need Eat(). Split interfaces by capability.', 9),
('go-oop', 'lsp-isp', 'true-false', 'easy', 'Go''s standard library follows ISP with io.Reader and io.Writer.', NULL, NULL, 'true', 'io.Reader has just Read(). io.Writer has just Write(). io.ReadWriter composes both. Classic ISP.', 10),
('go-oop', 'lsp-isp', 'multiple-choice', 'hard', 'What is the benefit of small interfaces for testing?', NULL, '["Smaller test files", "Easier to mock - fewer methods to implement", "Faster tests", "No benefit"]', '1', 'Mocking a 1-method interface is trivial. Mocking a 10-method interface requires implementing all methods.', 11),
('go-oop', 'lsp-isp', 'code-output', 'medium', 'How does this violate ISP?', 'type Printer interface {\n    Print(doc Document)\n    Scan() Document\n    Fax(doc Document)\n}', '["It doesn''t", "Simple printers must implement Scan/Fax they don''t support", "Too few methods", "Wrong return types"]', '1', 'A basic printer without scanner/fax must still implement those methods. Split into Printer, Scanner, Faxer interfaces.', 12),
('go-oop', 'lsp-isp', 'identify-bug', 'hard', 'What is the design problem?', 'func ProcessDocument(p Printer) {\n    p.Print(doc)\n    // Never uses Scan or Fax\n}', '["Nothing wrong", "ProcessDocument depends on Printer interface with methods it doesn''t use", "Should use concrete type", "Missing error handling"]', '1', 'ProcessDocument only needs Print but depends on full Printer interface. Should accept smaller interface.', 13),
('go-oop', 'lsp-isp', 'multiple-choice', 'medium', 'What is the Go idiom that aligns with ISP?', NULL, '["Accept large interfaces", "Accept interfaces, return concrete types", "Define interfaces where they are used (consumer)", "Always use interface{}"]', '2', 'Define interfaces at the consumer. ProcessDocument defines type Printer interface { Print() } locally if needed.', 14),
('go-oop', 'lsp-isp', 'true-false', 'hard', 'LSP violations can cause runtime errors that are hard to debug.', NULL, NULL, 'true', 'When a "substitute" type has unexpected behavior, failures happen at runtime in unexpected places.', 15);

-- DIP and DI
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'dip-di';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'dip-di', 'multiple-choice', 'easy', 'What is Dependency Inversion Principle?', NULL, '["High-level modules should depend on low-level modules", "High-level modules should depend on abstractions, not concretions", "Dependencies should be inverted at runtime", "Use dependency injection frameworks"]', '1', 'DIP: high-level policy should not depend on low-level detail. Both should depend on abstractions (interfaces).', 1),
('go-oop', 'dip-di', 'code-output', 'medium', 'Does this follow DIP?', 'type OrderService struct {\n    db *PostgresDB\n}\nfunc NewOrderService() *OrderService {\n    return &OrderService{db: &PostgresDB{}}\n}', '["Yes", "No - OrderService directly depends on PostgresDB (concrete)", "Partially", "Cannot determine"]', '1', 'OrderService depends on concrete PostgresDB. Should depend on interface like Repository instead.', 2),
('go-oop', 'dip-di', 'multiple-choice', 'medium', 'How do you fix the DIP violation above?', NULL, '["Use reflection", "Depend on interface: type OrderService struct { repo Repository }", "Use global variable", "Add more methods to PostgresDB"]', '1', 'Define interface Repository, make OrderService depend on it. Inject PostgresDB which implements Repository.', 3),
('go-oop', 'dip-di', 'true-false', 'easy', 'Dependency Injection is the same as Dependency Inversion.', NULL, NULL, 'false', 'DIP is the principle (depend on abstractions). DI is a technique to achieve DIP (pass dependencies from outside).', 4),
('go-oop', 'dip-di', 'code-output', 'easy', 'What is dependency injection?', 'func NewService(repo Repository) *Service {\n    return &Service{repo: repo}\n}', '["Creating dependencies inside the function", "Receiving dependencies as parameters", "Using global state", "Hardcoding implementations"]', '1', 'DI: receive dependencies from outside (constructor, method, or field injection) rather than creating them.', 5),
('go-oop', 'dip-di', 'multiple-choice', 'medium', 'What is the main benefit of DI for testing?', NULL, '["Faster tests", "Can inject mock/stub implementations", "Smaller test files", "No setup needed"]', '1', 'DI allows injecting test doubles (mocks, stubs, fakes) instead of real dependencies. Makes unit testing possible.', 6),
('go-oop', 'dip-di', 'code-output', 'medium', 'What type of injection is this?', 'type Handler struct {\n    logger Logger\n}\n\nfunc NewHandler(l Logger) *Handler {\n    return &Handler{logger: l}\n}', '["Field injection", "Constructor injection", "Method injection", "Property injection"]', '1', 'Constructor injection: dependencies are passed when creating the object via New* function.', 7),
('go-oop', 'dip-di', 'identify-bug', 'hard', 'What is the DIP problem?', 'package order\n\nimport "myapp/postgres"\n\ntype Service struct {\n    db *postgres.Client\n}', '["No problem", "order package depends on postgres package (low-level detail)", "Missing interface", "Should use global"]', '1', 'High-level order package imports low-level postgres package. Define interface in order package, implement in postgres.', 8),
('go-oop', 'dip-di', 'multiple-choice', 'hard', 'Where should interfaces be defined for DIP?', NULL, '["In the implementing package", "In the consuming (high-level) package", "In a shared package", "Anywhere"]', '1', 'Consumer defines interfaces. order.Repository is defined in order package, implemented by postgres package.', 9),
('go-oop', 'dip-di', 'code-output', 'medium', 'Why is this easier to test?', 'type Service struct {\n    notifier Notifier\n}\n\nfunc (s *Service) Process() {\n    s.notifier.Notify("done")\n}', '["It''s not easier", "Can inject MockNotifier without sending real notifications", "Faster execution", "Less code"]', '1', 'Inject a MockNotifier that records calls instead of sending real emails/SMS. Verify behavior without side effects.', 10),
('go-oop', 'dip-di', 'true-false', 'medium', 'Go requires a DI framework like Wire or Dig.', NULL, NULL, 'false', 'Go''s simplicity allows manual DI via constructors. Frameworks help with large apps but are not required.', 11),
('go-oop', 'dip-di', 'multiple-choice', 'medium', 'What is "inversion" in Dependency Inversion?', NULL, '["Code runs backwards", "Traditional: high depends on low. Inverted: both depend on abstractions", "Using reverse loops", "Inverting function calls"]', '1', 'Traditional design has high-level depending on low-level. DIP inverts this - both depend on shared abstractions.', 12),
('go-oop', 'dip-di', 'code-output', 'hard', 'Which is correct for DIP?', NULL, '["import concrete package in high-level module", "Define interface in high-level, implement in low-level", "High-level returns concrete types", "Avoid interfaces"]', '1', 'High-level defines what it needs (interface). Low-level provides implementation. No import from high to low.', 13),
('go-oop', 'dip-di', 'identify-bug', 'medium', 'What makes this hard to test?', 'func ProcessOrder(order Order) error {\n    db := sql.Open("postgres", connString)\n    // use db\n}', '["Nothing", "Creates database connection inside - cannot inject mock", "Missing error check", "Wrong function signature"]', '1', 'Function creates its own dependency. Cannot test without real database. Should accept db as parameter.', 14),
('go-oop', 'dip-di', 'multiple-choice', 'easy', 'What is a common DI pattern in Go?', NULL, '["Service locator", "Constructor injection with New* functions", "Singleton pattern", "Ambient context"]', '1', 'Go typically uses constructor injection: NewService(dep1, dep2) creates service with injected dependencies.', 15);
