-- Quiz Questions for Go OOP: Embedding and Generics
-- Section: embedding-generics (15 questions)

DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'embedding-generics';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'embedding-generics', 'multiple-choice', 'easy', 'What happens when you embed a struct without a field name?', NULL, '["Compilation error", "Fields and methods are promoted to the outer type", "The embedded struct is ignored", "Only fields are accessible"]', '1', 'When you embed a struct without a field name, Go promotes all its fields and methods to the outer type, making them directly accessible.', 1),
('go-oop', 'embedding-generics', 'code-output', 'medium', 'What does this code print?', E'type Person struct {\n    Name string\n}\n\ntype Employee struct {\n    Person\n    ID string\n}\n\nemp := Employee{\n    Person: Person{Name: "Alice"},\n    ID: "E1",\n}\nfmt.Println(emp.Name)', '["Compilation error", "Alice", "E1", "{Alice}"]', '1', 'The Name field is promoted from Person to Employee, so emp.Name accesses Person.Name directly, printing "Alice".', 2),
('go-oop', 'embedding-generics', 'true-false', 'easy', 'Embedding in Go is the same as inheritance in Java.', NULL, NULL, 'false', 'Embedding is composition, not inheritance. An Employee is not a Person; it has a Person. The fields and methods are promoted, but there is no "is-a" relationship.', 3),
('go-oop', 'embedding-generics', 'multiple-choice', 'medium', 'What is method shadowing in Go?', NULL, '["When a method is deleted", "When the outer type defines a method with the same name as the embedded type", "When two structs have the same method", "When a method returns nil"]', '1', 'Method shadowing occurs when the outer type defines a method with the same name as the embedded type. The outer method takes priority, but the original is still accessible via the embedded field.', 4),
('go-oop', 'embedding-generics', 'code-output', 'medium', 'What does ts.Log("hi") print?', E'type Logger struct{}\n\nfunc (l Logger) Log(msg string) {\n    fmt.Println("LOG:", msg)\n}\n\ntype TSLogger struct {\n    Logger\n}\n\nfunc (t TSLogger) Log(msg string) {\n    fmt.Println("TS:", msg)\n}\n\nts := TSLogger{}\nts.Log("hi")', '["LOG: hi", "TS: hi", "Both LOG: hi and TS: hi", "Compilation error"]', '1', 'TSLogger.Log shadows Logger.Log. When calling ts.Log(), the outer type''s method is used, printing "TS: hi". The original is accessible via ts.Logger.Log().', 5),
('go-oop', 'embedding-generics', 'multiple-choice', 'easy', 'What does interface embedding do?', NULL, '["Creates a new interface type", "Combines method sets from multiple interfaces", "Inherits from another interface", "Copies methods to a struct"]', '1', 'Interface embedding combines method sets from multiple interfaces. For example, io.ReadWriter embeds io.Reader and io.Writer, requiring types to implement both.', 6),
('go-oop', 'embedding-generics', 'true-false', 'medium', 'A type that implements both io.Reader and io.Writer automatically satisfies io.ReadWriter.', NULL, NULL, 'true', 'Since io.ReadWriter embeds both io.Reader and io.Writer, any type implementing both interfaces satisfies io.ReadWriter automatically.', 7),
('go-oop', 'embedding-generics', 'multiple-choice', 'easy', 'What is the syntax for declaring a generic function in Go?', NULL, '["func Name<T>(x T)", "func Name[T any](x T)", "func Name(T)(x T)", "func<T> Name(x T)"]', '1', 'Go uses square brackets for type parameters: func Name[T any](x T). The type parameter goes before the regular parameters.', 8),
('go-oop', 'embedding-generics', 'code-output', 'medium', 'What does First([]int{10, 20, 30}) return?', E'func First[T any](items []T) (T, bool) {\n    if len(items) == 0 {\n        var zero T\n        return zero, false\n    }\n    return items[0], true\n}', '["10, true", "10, false", "0, false", "Compilation error"]', '0', 'The slice has elements, so First returns the first element (10) and true to indicate success.', 9),
('go-oop', 'embedding-generics', 'multiple-choice', 'medium', 'Why would you use a type constraint instead of "any"?', NULL, '["To make code faster", "To allow operations like + or < that require specific types", "To reduce memory usage", "any is deprecated"]', '1', 'The "any" constraint allows any type but limits what operations you can perform. Type constraints let you specify which types are allowed, enabling operations like arithmetic (+) or comparison (<).', 10),
('go-oop', 'embedding-generics', 'code-output', 'hard', 'Will this code compile?', E'func Add[T any](a, b T) T {\n    return a + b\n}', '["Yes, and works for all types", "No, + is not allowed with any constraint", "Yes, but only for numbers", "No, syntax error"]', '1', 'This code will not compile because the + operator is not defined for all types. You need a constraint like "type Number interface { int | float64 }" to allow arithmetic.', 11),
('go-oop', 'embedding-generics', 'multiple-choice', 'medium', 'What is the purpose of the comparable constraint?', NULL, '["To compare performance", "To allow types that support == and != operators", "To sort slices", "To compare interfaces"]', '1', 'The comparable constraint includes all types that support == and !=. This is required for map keys and equality checks in generic functions.', 12),
('go-oop', 'embedding-generics', 'true-false', 'medium', 'Slices can be used with the comparable constraint.', NULL, NULL, 'false', 'Slices, maps, and functions are not comparable in Go. They cannot be used with == or as map keys, so they do not satisfy the comparable constraint.', 13),
('go-oop', 'embedding-generics', 'code-output', 'medium', 'What type is stack after this declaration?', E'type Stack[T any] struct {\n    items []T\n}\n\nstack := &Stack[string]{}', '["Stack[any]", "Stack[string]", "Stack", "*Stack[string]"]', '3', 'The variable stack is a pointer to Stack[string]. The type parameter is string, and the & creates a pointer.', 14),
('go-oop', 'embedding-generics', 'multiple-choice', 'hard', 'When should you use generics vs interfaces in Go?', NULL, '["Always use generics", "Generics for same algorithm with different types, interfaces for different behaviors with same signature", "Always use interfaces", "They are interchangeable"]', '1', 'Use generics when you have the same algorithm that should work with different types (like a Stack or Map). Use interfaces when you need different behaviors that share a common signature (like different payment methods).', 15);
