-- Quiz Questions for Go OOP Part 6: Advanced Topics
-- Sections: clean-architecture, testing-oop

-- Clean Architecture
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'clean-architecture';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'clean-architecture', 'multiple-choice', 'easy', 'What is the core idea of Clean Architecture?', NULL, '["Fastest possible code", "Dependency rule: inner layers don''t depend on outer layers", "Minimum code lines", "Single file applications"]', '1', 'Clean Architecture: dependencies point inward. Domain/business logic doesn''t depend on frameworks, DB, or UI.', 1),
('go-oop', 'clean-architecture', 'multiple-choice', 'easy', 'What is the innermost layer in Clean Architecture?', NULL, '["Database", "Entities/Domain - core business objects and rules", "HTTP handlers", "Configuration"]', '1', 'Entities/Domain: pure business logic. No dependencies on frameworks, databases, or external systems.', 2),
('go-oop', 'clean-architecture', 'code-output', 'medium', 'What layer contains use cases?', NULL, '["Domain/Entities", "Application/Use Cases - business workflows", "Infrastructure", "Presentation"]', '1', 'Use Cases (Application layer): orchestrate domain entities to fulfill business requirements.', 3),
('go-oop', 'clean-architecture', 'true-false', 'medium', 'Domain entities should import database packages.', NULL, NULL, 'false', 'Domain is the inner layer. It must not import anything from outer layers like database or HTTP.', 4),
('go-oop', 'clean-architecture', 'multiple-choice', 'medium', 'What is a Repository in Clean Architecture?', NULL, '["Database library", "Interface in domain, implemented in infrastructure", "HTTP client", "Configuration file"]', '1', 'Repository: interface defined in domain (what we need), implementation in infrastructure (how we do it).', 5),
('go-oop', 'clean-architecture', 'code-output', 'hard', 'Which direction should imports flow?', NULL, '["Outer can import inner (handlers import domain)", "Inner imports outer", "Both directions freely", "No imports allowed"]', '0', 'Imports flow inward: infrastructure/handlers can import domain, but domain never imports handlers.', 6),
('go-oop', 'clean-architecture', 'identify-bug', 'hard', 'What violates Clean Architecture?', 'package domain\n\nimport (\n    "database/sql"\n    "encoding/json"\n)', '["Nothing wrong", "Domain importing database/sql - depends on infrastructure detail", "Missing import", "Wrong package name"]', '1', 'Domain should not import database/sql. Define Repository interface in domain, implement with sql elsewhere.', 7),
('go-oop', 'clean-architecture', 'multiple-choice', 'medium', 'What belongs in the Infrastructure layer?', NULL, '["Business rules", "Database implementations, HTTP clients, external APIs", "Use cases", "Domain entities"]', '1', 'Infrastructure: concrete implementations of interfaces. Database repos, API clients, message queues.', 8),
('go-oop', 'clean-architecture', 'true-false', 'medium', 'Use cases should depend on interfaces, not concrete implementations.', NULL, NULL, 'true', 'Use cases depend on Repository interface, not PostgresRepository. Enables testing and swapping implementations.', 9),
('go-oop', 'clean-architecture', 'code-output', 'medium', 'Where should interfaces be defined?', NULL, '["In the implementing package", "In the package that uses them (consumer)", "In a shared package", "In main"]', '1', 'Define interfaces where they are used. UserUseCase defines UserRepository interface, postgres package implements it.', 10),
('go-oop', 'clean-architecture', 'multiple-choice', 'hard', 'What is Dependency Injection in Clean Architecture?', NULL, '["Import statement", "Pass concrete implementations to inner layers from outside", "Global variables", "Reflection magic"]', '1', 'DI: outer layers create concrete implementations and inject them into inner layers via constructors.', 11),
('go-oop', 'clean-architecture', 'identify-bug', 'medium', 'What is the design smell?', 'type OrderService struct {\n    db *sql.DB\n}', '["Nothing wrong", "Service directly depends on *sql.DB instead of Repository interface", "Missing methods", "Wrong name"]', '1', 'OrderService should depend on OrderRepository interface, not concrete *sql.DB. Violates DIP.', 12),
('go-oop', 'clean-architecture', 'true-false', 'hard', 'Clean Architecture makes testing easier because business logic is isolated.', NULL, NULL, 'true', 'Domain and use cases have no external dependencies. Test with mock repositories. No database needed.', 13),
('go-oop', 'clean-architecture', 'multiple-choice', 'medium', 'What is typical Go project structure for Clean Architecture?', NULL, '["Everything in main.go", "cmd/, internal/domain/, internal/usecase/, internal/repository/, internal/handler/", "One package only", "Random folders"]', '1', 'Separate packages by layer: domain (entities), usecase (application), repository (data access), handler (presentation).', 14),
('go-oop', 'clean-architecture', 'code-output', 'hard', 'Where does main() fit?', NULL, '["Domain layer", "Composition root - wires everything together, outermost", "Use case layer", "Repository layer"]', '1', 'main() is the composition root. It creates concrete implementations and injects them. Highest level of the app.', 15);

-- Testing OOP Code
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'testing-oop';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'testing-oop', 'multiple-choice', 'easy', 'What is a mock in testing?', NULL, '["Real implementation", "Object that simulates behavior and records calls", "Database", "Random data"]', '1', 'Mock: test double that simulates behavior and allows verification of how it was called.', 1),
('go-oop', 'testing-oop', 'multiple-choice', 'easy', 'What is the difference between mock and stub?', NULL, '["Same thing", "Stub returns canned data, mock also verifies interactions", "Mock is faster", "Stub is for production"]', '1', 'Stub: returns predetermined responses. Mock: also records calls for verification (was method called with right args?).', 2),
('go-oop', 'testing-oop', 'code-output', 'medium', 'What makes this code testable?', 'type OrderService struct {\n    repo OrderRepository  // interface\n}\nfunc NewOrderService(repo OrderRepository) *OrderService {\n    return &OrderService{repo: repo}\n}', '["Nothing special", "Dependency injection - can inject mock repository", "The struct name", "The constructor"]', '1', 'Constructor injection allows passing mock OrderRepository for testing without real database.', 3),
('go-oop', 'testing-oop', 'true-false', 'easy', 'Go requires a mocking framework to create test doubles.', NULL, NULL, 'false', 'Go interfaces make manual mocks easy. Just create a struct implementing the interface. No framework needed.', 4),
('go-oop', 'testing-oop', 'code-output', 'medium', 'What is table-driven testing?', 'func TestAdd(t *testing.T) {\n    tests := []struct{\n        a, b, want int\n    }{{1, 2, 3}, {0, 0, 0}, {-1, 1, 0}}\n    for _, tt := range tests {\n        got := Add(tt.a, tt.b)\n        if got != tt.want {\n            t.Errorf("Add(%d,%d) = %d, want %d", tt.a, tt.b, got, tt.want)\n        }\n    }\n}', '["Random testing", "Define test cases as data, iterate through them", "Parallel testing", "UI testing"]', '1', 'Table-driven: test cases as slice of structs. Loop runs same logic with different inputs. Go idiom.', 5),
('go-oop', 'testing-oop', 'multiple-choice', 'medium', 'What is the benefit of small interfaces for testing?', NULL, '["Faster execution", "Easier to create mocks with fewer methods", "Required by Go", "No benefit"]', '1', 'Small interface = small mock. Mocking a 1-method interface is trivial. Mocking 10 methods is tedious.', 6),
('go-oop', 'testing-oop', 'code-output', 'hard', 'What does this mock enable?', 'type MockRepo struct {\n    SaveCalled bool\n    SaveArg    User\n    SaveErr    error\n}\nfunc (m *MockRepo) Save(u User) error {\n    m.SaveCalled = true\n    m.SaveArg = u\n    return m.SaveErr\n}', '["Nothing", "Verify Save was called, with what argument, control return value", "Performance testing", "Integration testing"]', '1', 'Mock records call (SaveCalled), captures argument (SaveArg), and allows controlling return (SaveErr).', 7),
('go-oop', 'testing-oop', 'identify-bug', 'hard', 'What makes this hard to test?', 'func ProcessOrder(orderID string) error {\n    db := sql.Open("postgres", connStr)\n    order := db.Query("SELECT * FROM orders WHERE id = ?", orderID)\n    // process order\n}', '["Nothing wrong", "Creates own dependency - cannot inject mock database", "Missing error handling", "Wrong SQL syntax"]', '1', 'Function creates its own database connection. Cannot test without real database. Accept db as parameter.', 8),
('go-oop', 'testing-oop', 'multiple-choice', 'medium', 'What is a fake vs mock?', NULL, '["Same thing", "Fake has working implementation (in-memory DB), mock simulates behavior", "Fake is slower", "Mock is in-memory"]', '1', 'Fake: simplified working implementation (in-memory cache). Mock: simulates and records for verification.', 9),
('go-oop', 'testing-oop', 'true-false', 'medium', 'Testing design patterns proves they are implemented correctly.', NULL, NULL, 'true', 'Tests verify pattern behavior: Strategy switches correctly, Observer notifies all subscribers, etc.', 10),
('go-oop', 'testing-oop', 'code-output', 'medium', 'How do you test Observer pattern?', NULL, '["Skip testing", "Create mock observers, verify they receive notifications", "Only test publisher", "Manual testing"]', '1', 'Mock Observer implementing Update(). Call Publish(), verify mock''s Update() was called with correct message.', 11),
('go-oop', 'testing-oop', 'multiple-choice', 'hard', 'What is the Arrange-Act-Assert pattern?', NULL, '["Random order", "Setup test data, execute code, verify results", "Three test files", "UI pattern"]', '1', 'AAA: Arrange (setup), Act (call function), Assert (verify). Clear structure for each test.', 12),
('go-oop', 'testing-oop', 'code-output', 'medium', 'What does t.Run enable?', 'func TestCalculator(t *testing.T) {\n    t.Run("add", func(t *testing.T) { ... })\n    t.Run("subtract", func(t *testing.T) { ... })\n}', '["Parallel execution", "Subtests with names, better organization and output", "Slower tests", "Nothing special"]', '1', 't.Run creates named subtests. Better output (shows which failed), can run specific subtest: go test -run Add.', 13),
('go-oop', 'testing-oop', 'identify-bug', 'medium', 'What is missing in this test?', 'func TestSave(t *testing.T) {\n    repo := &MockRepo{}\n    service := NewUserService(repo)\n    service.CreateUser(User{Name: "Alice"})\n    // End of test\n}', '["Nothing missing", "Missing assertion - doesn''t verify anything was called", "Missing error handling", "Wrong mock"]', '1', 'Test calls CreateUser but never asserts. Should check repo.SaveCalled == true and SaveArg.Name == "Alice".', 14),
('go-oop', 'testing-oop', 'multiple-choice', 'hard', 'When should you use integration tests over unit tests?', NULL, '["Always", "When testing interactions between components (real DB, HTTP)", "Never", "Only for UI"]', '1', 'Integration tests verify components work together. Unit tests verify isolated logic. Both are valuable.', 15);
