-- Quiz Questions for Go OOP Part 4: Design Patterns
-- Sections: creational-patterns, structural-patterns, behavioral-patterns

-- Creational Patterns
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'creational-patterns';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'creational-patterns', 'multiple-choice', 'easy', 'What do creational patterns help with?', NULL, '["Object creation mechanisms", "Object relationships", "Algorithm selection", "Code organization"]', '0', 'Creational patterns abstract object creation, making systems independent of how objects are created.', 1),
('go-oop', 'creational-patterns', 'code-output', 'medium', 'What pattern is this?', 'func NewLogger(logType string) Logger {\n    switch logType {\n    case "file": return &FileLogger{}\n    case "console": return &ConsoleLogger{}\n    }\n    return &NullLogger{}\n}', '["Builder", "Factory", "Singleton", "Prototype"]', '1', 'Factory pattern: function returns different implementations based on input parameter.', 2),
('go-oop', 'creational-patterns', 'multiple-choice', 'medium', 'When should you use Factory pattern?', NULL, '["When object creation is simple", "When creation logic is complex or type is determined at runtime", "For all objects", "Only for interfaces"]', '1', 'Factory encapsulates complex creation logic or when the exact type depends on runtime conditions.', 3),
('go-oop', 'creational-patterns', 'code-output', 'medium', 'What pattern enables this?', 'query := NewQueryBuilder().\n    Select("name", "email").\n    From("users").\n    Where("active = true").\n    Build()', '["Factory", "Builder", "Singleton", "Abstract Factory"]', '1', 'Builder pattern: construct complex objects step-by-step with method chaining.', 4),
('go-oop', 'creational-patterns', 'true-false', 'easy', 'Builder pattern is useful when an object has many optional parameters.', NULL, NULL, 'true', 'Builder handles many optional parameters elegantly, avoiding constructors with numerous parameters.', 5),
('go-oop', 'creational-patterns', 'code-output', 'hard', 'What ensures only one instance?', 'var (\n    instance *Config\n    once     sync.Once\n)\n\nfunc GetConfig() *Config {\n    once.Do(func() {\n        instance = &Config{}\n    })\n    return instance\n}', '["Factory", "Builder", "Singleton with sync.Once", "Prototype"]', '2', 'Singleton pattern using sync.Once ensures the initialization runs exactly once, even with concurrent calls.', 6),
('go-oop', 'creational-patterns', 'multiple-choice', 'hard', 'Why is Singleton considered problematic?', NULL, '["It''s slow", "Hidden dependencies, global state, hard to test", "Too much code", "Go doesn''t support it"]', '1', 'Singletons create hidden dependencies, make testing difficult (can''t inject mocks), and introduce global state.', 7),
('go-oop', 'creational-patterns', 'identify-bug', 'hard', 'What is wrong with this Singleton?', 'var instance *Config\n\nfunc GetConfig() *Config {\n    if instance == nil {\n        instance = &Config{}\n    }\n    return instance\n}', '["Nothing wrong", "Race condition - not thread-safe", "Should return interface", "Missing sync.Once"]', '1', 'Multiple goroutines could pass the nil check simultaneously, creating multiple instances. Use sync.Once.', 8),
('go-oop', 'creational-patterns', 'multiple-choice', 'medium', 'What is Abstract Factory?', NULL, '["Factory of factories", "Factory that creates families of related objects", "Abstract class with factory method", "Factory using generics"]', '1', 'Abstract Factory creates families of related objects (e.g., UI factory creating buttons, dialogs for specific OS).', 9),
('go-oop', 'creational-patterns', 'code-output', 'easy', 'Which is idiomatic Go for Builder?', NULL, '["Separate Builder class", "Functional options pattern", "Both are common in Go", "Neither"]', '2', 'Go uses both traditional Builder (method chaining) and functional options. Both are idiomatic.', 10),
('go-oop', 'creational-patterns', 'true-false', 'medium', 'Functional options can be seen as a variant of Builder pattern.', NULL, NULL, 'true', 'Functional options provide builder-like capabilities: construct objects step by step with sensible defaults.', 11),
('go-oop', 'creational-patterns', 'multiple-choice', 'medium', 'What should Builder.Build() return when validation fails?', NULL, '["Nil", "(*Type, error) to indicate failure", "Panic", "Zero value"]', '1', 'Go idiom: return (*Type, error) so callers can handle validation failures.', 12),
('go-oop', 'creational-patterns', 'code-output', 'hard', 'What is the key method in this Factory?', 'type DBFactory interface {\n    CreateConnection() Connection\n    CreateQuery() Query\n    CreateTransaction() Transaction\n}', '["Constructor method", "Family of related objects - Abstract Factory", "Simple Factory", "Builder"]', '1', 'Interface with multiple Create* methods for related objects indicates Abstract Factory pattern.', 13),
('go-oop', 'creational-patterns', 'multiple-choice', 'easy', 'What is the Go alternative to Singleton for configuration?', NULL, '["Just use Singleton", "Dependency injection - pass config to constructors", "Global variables", "Environment variables only"]', '1', 'Prefer DI: create config once in main(), pass to components that need it. Explicit, testable dependencies.', 14),
('go-oop', 'creational-patterns', 'true-false', 'hard', 'sync.Once makes Singleton thread-safe even under high concurrency.', NULL, NULL, 'true', 'sync.Once guarantees the function runs exactly once, regardless of how many goroutines call it.', 15);

-- Structural Patterns
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'structural-patterns';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'structural-patterns', 'multiple-choice', 'easy', 'What do structural patterns help with?', NULL, '["Object creation", "Composing objects into larger structures", "Algorithm selection", "State management"]', '1', 'Structural patterns compose objects and classes into larger structures while keeping them flexible.', 1),
('go-oop', 'structural-patterns', 'code-output', 'medium', 'What pattern is this?', 'type OldAPI struct{}\nfunc (o *OldAPI) LegacyRequest() string { return "old" }\n\ntype Adapter struct {\n    old *OldAPI\n}\nfunc (a *Adapter) NewRequest() string { return a.old.LegacyRequest() }', '["Decorator", "Adapter", "Proxy", "Bridge"]', '1', 'Adapter converts one interface to another. Here, Adapter makes OldAPI work with NewRequest interface.', 2),
('go-oop', 'structural-patterns', 'multiple-choice', 'medium', 'When should you use Adapter pattern?', NULL, '["Always", "When integrating with incompatible interfaces (legacy code, third-party libs)", "For new code only", "To improve performance"]', '1', 'Adapter bridges incompatible interfaces, often used when integrating legacy code or third-party libraries.', 3),
('go-oop', 'structural-patterns', 'code-output', 'medium', 'What pattern adds behavior dynamically?', 'type Logger interface { Log(msg string) }\n\ntype TimestampLogger struct {\n    wrapped Logger\n}\nfunc (t *TimestampLogger) Log(msg string) {\n    t.wrapped.Log(time.Now().String() + ": " + msg)\n}', '["Adapter", "Decorator", "Proxy", "Facade"]', '1', 'Decorator wraps an object to add behavior (timestamp) while maintaining the same interface.', 4),
('go-oop', 'structural-patterns', 'true-false', 'medium', 'Decorator and wrapper are essentially the same pattern.', NULL, NULL, 'true', 'Decorator is also called wrapper. Both terms describe adding behavior by wrapping an object.', 5),
('go-oop', 'structural-patterns', 'multiple-choice', 'medium', 'What is the key characteristic of Decorator?', NULL, '["Creates new interface", "Implements same interface as wrapped object", "Changes wrapped object", "Requires inheritance"]', '1', 'Decorator implements the same interface as the wrapped object, allowing transparent wrapping.', 6),
('go-oop', 'structural-patterns', 'code-output', 'medium', 'What pattern simplifies a complex subsystem?', 'type OrderFacade struct {\n    inventory *Inventory\n    payment   *Payment\n    shipping  *Shipping\n}\nfunc (f *OrderFacade) PlaceOrder(o Order) error {\n    // Coordinates all subsystems\n}', '["Adapter", "Decorator", "Facade", "Bridge"]', '2', 'Facade provides a simple interface to a complex subsystem, hiding the complexity of multiple components.', 7),
('go-oop', 'structural-patterns', 'multiple-choice', 'easy', 'When is Facade pattern useful?', NULL, '["When subsystem is simple", "When you need a simple interface to a complex subsystem", "For single objects", "For algorithms"]', '1', 'Facade simplifies interaction with complex systems (e.g., video conversion with codecs, formats, encoders).', 8),
('go-oop', 'structural-patterns', 'code-output', 'hard', 'What pattern is this?', 'type CachedDB struct {\n    real  Database\n    cache map[string]interface{}\n}\nfunc (c *CachedDB) Get(key string) interface{} {\n    if v, ok := c.cache[key]; ok { return v }\n    v := c.real.Get(key)\n    c.cache[key] = v\n    return v\n}', '["Decorator", "Adapter", "Proxy (caching proxy)", "Bridge"]', '2', 'Proxy controls access to an object. Caching proxy adds caching before delegating to the real object.', 9),
('go-oop', 'structural-patterns', 'multiple-choice', 'hard', 'How do Proxy and Decorator differ?', NULL, '["They are identical", "Proxy controls access, Decorator adds behavior", "Decorator controls access, Proxy adds behavior", "Different languages use different names"]', '1', 'Proxy controls access (caching, lazy loading, access control). Decorator adds new behavior.', 10),
('go-oop', 'structural-patterns', 'identify-bug', 'medium', 'What is missing in this Decorator?', 'type LoggingHandler struct {\n    next http.Handler\n}\nfunc (l *LoggingHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {\n    log.Printf("%s %s", r.Method, r.URL)\n    // Missing something\n}', '["Nothing missing", "Must call l.next.ServeHTTP(w, r) to delegate", "Missing return", "Should panic"]', '1', 'Decorator must delegate to wrapped object. Without l.next.ServeHTTP(), the actual handler never runs.', 11),
('go-oop', 'structural-patterns', 'true-false', 'medium', 'Go''s io.Reader wrapping (like bufio.Reader) uses Decorator pattern.', NULL, NULL, 'true', 'bufio.Reader wraps io.Reader, adding buffering while maintaining the Reader interface. Classic Decorator.', 12),
('go-oop', 'structural-patterns', 'code-output', 'easy', 'Can you chain multiple decorators?', NULL, '["No, only one decorator at a time", "Yes, each decorator wraps the previous", "Only with special syntax", "Requires framework"]', '1', 'Decorators chain: TimestampLogger{MetricsLogger{BaseLogger{}}}. Each wraps the next.', 13),
('go-oop', 'structural-patterns', 'multiple-choice', 'medium', 'In Go, how is Adapter typically implemented?', NULL, '["Inheritance", "Struct embedding with method forwarding", "Reflection", "Code generation"]', '1', 'Go uses struct embedding or delegation. Adapter struct embeds/contains adaptee and provides new methods.', 14),
('go-oop', 'structural-patterns', 'code-output', 'hard', 'What makes http.HandlerFunc an adapter?', 'type HandlerFunc func(http.ResponseWriter, *http.Request)\nfunc (f HandlerFunc) ServeHTTP(w http.ResponseWriter, r *http.Request) {\n    f(w, r)\n}', '["It doesn''t", "Adapts a function to the Handler interface", "It''s a decorator", "It''s a proxy"]', '1', 'HandlerFunc adapts a plain function to implement http.Handler interface. Function becomes an interface implementation.', 15);

-- Behavioral Patterns
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'behavioral-patterns';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'behavioral-patterns', 'multiple-choice', 'easy', 'What do behavioral patterns focus on?', NULL, '["Object creation", "Object composition", "Communication and responsibility between objects", "Memory management"]', '2', 'Behavioral patterns deal with algorithms, assignment of responsibilities, and communication between objects.', 1),
('go-oop', 'behavioral-patterns', 'code-output', 'medium', 'What pattern is this?', 'type PaymentStrategy interface {\n    Pay(amount float64) error\n}\n\ntype CreditCard struct{}\ntype PayPal struct{}\ntype Crypto struct{}\n\nfunc Checkout(strategy PaymentStrategy, amount float64) {\n    strategy.Pay(amount)\n}', '["Factory", "Strategy", "Command", "Observer"]', '1', 'Strategy pattern: define family of algorithms, encapsulate each, make them interchangeable.', 2),
('go-oop', 'behavioral-patterns', 'multiple-choice', 'medium', 'In Go, Strategy can be simplified to?', NULL, '["Abstract class", "Function type instead of interface", "Global variable", "Singleton"]', '1', 'Go simplifies Strategy with function types: type PaymentFunc func(float64) error. No interface needed.', 3),
('go-oop', 'behavioral-patterns', 'code-output', 'medium', 'What pattern is this?', 'type Subject struct {\n    observers []Observer\n}\nfunc (s *Subject) Notify(event string) {\n    for _, o := range s.observers {\n        o.Update(event)\n    }\n}\nfunc (s *Subject) Subscribe(o Observer) {\n    s.observers = append(s.observers, o)\n}', '["Strategy", "Observer", "Command", "Mediator"]', '1', 'Observer pattern: subject notifies multiple observers when state changes.', 4),
('go-oop', 'behavioral-patterns', 'true-false', 'medium', 'In Go, channels can replace Observer pattern for some use cases.', NULL, NULL, 'true', 'Channels provide built-in pub/sub mechanism. Often simpler than implementing full Observer in Go.', 5),
('go-oop', 'behavioral-patterns', 'code-output', 'hard', 'What pattern encapsulates a request?', 'type Command interface {\n    Execute()\n    Undo()\n}\n\ntype PasteCommand struct {\n    editor *Editor\n    text   string\n}\nfunc (c *PasteCommand) Execute() { c.editor.Insert(c.text) }\nfunc (c *PasteCommand) Undo() { c.editor.Delete(len(c.text)) }', '["Strategy", "Observer", "Command", "State"]', '2', 'Command pattern encapsulates a request as an object, allowing undo, queuing, and logging.', 6),
('go-oop', 'behavioral-patterns', 'multiple-choice', 'medium', 'When is Command pattern useful?', NULL, '["Simple operations", "When you need undo/redo, queuing, or transaction logging", "For all function calls", "Only in GUIs"]', '1', 'Command shines when you need to queue, log, or undo operations. Common in editors and transaction systems.', 7),
('go-oop', 'behavioral-patterns', 'code-output', 'medium', 'What defines the algorithm skeleton?', 'type Report interface {\n    GatherData() []Data\n    FormatOutput([]Data) string\n}\n\nfunc Generate(r Report) string {\n    data := r.GatherData()\n    return r.FormatOutput(data)\n}', '["Strategy", "Observer", "Template Method", "Factory"]', '2', 'Template Method: Generate defines algorithm skeleton, subclasses implement GatherData and FormatOutput.', 8),
('go-oop', 'behavioral-patterns', 'multiple-choice', 'hard', 'How does Go typically implement Template Method?', NULL, '["Abstract classes", "Interface + embedding", "Functions with callbacks", "Both interface and function approaches"]', '3', 'Go uses interfaces defining steps, or functions accepting callbacks. No abstract classes needed.', 9),
('go-oop', 'behavioral-patterns', 'identify-bug', 'hard', 'What is the thread-safety issue?', 'type Subject struct {\n    observers []Observer\n}\nfunc (s *Subject) Subscribe(o Observer) {\n    s.observers = append(s.observers, o)\n}\nfunc (s *Subject) Notify(event string) {\n    for _, o := range s.observers {\n        o.Update(event)\n    }\n}', '["No issue", "Concurrent Subscribe and Notify can cause race condition", "Missing Unsubscribe", "Wrong loop"]', '1', 'Append and iteration on same slice without mutex is not thread-safe. Add sync.RWMutex.', 10),
('go-oop', 'behavioral-patterns', 'true-false', 'easy', 'Strategy pattern allows changing algorithm at runtime.', NULL, NULL, 'true', 'Strategy encapsulates algorithms and makes them interchangeable. Switch strategies at runtime.', 11),
('go-oop', 'behavioral-patterns', 'code-output', 'medium', 'What is the benefit of Command over direct method calls?', NULL, '["Faster execution", "Can store commands for later, undo, or queue them", "Less code", "Type safety"]', '1', 'Commands are objects that can be stored, queued, serialized, undone. Direct calls cannot.', 12),
('go-oop', 'behavioral-patterns', 'multiple-choice', 'medium', 'What pattern would you use for undo/redo in a text editor?', NULL, '["Strategy", "Observer", "Command with history stack", "Factory"]', '2', 'Command pattern with a history stack. Push executed commands, pop for undo.', 13),
('go-oop', 'behavioral-patterns', 'code-output', 'hard', 'How can Strategy be a simple function in Go?', 'type SortFunc func([]int) []int\n\nfunc Process(data []int, sort SortFunc) []int {\n    return sort(data)\n}', '["This is not Strategy", "Function type as strategy - no interface needed", "Should use interface", "Missing implementation"]', '1', 'Go allows function types as strategies. Process accepts any func([]int)[]int without interface boilerplate.', 14),
('go-oop', 'behavioral-patterns', 'multiple-choice', 'medium', 'Observer pattern is also known as?', NULL, '["Strategy", "Publish-Subscribe", "Factory", "Singleton"]', '1', 'Observer is also called Publish-Subscribe. Subject publishes events, observers subscribe to receive them.', 15);
