-- Quiz Questions for Go OOP Part 5: LLD Problems
-- Sections: lld-intro, lld-cache, lld-rate-limiter, lld-parking-lot, lld-logger, lld-pub-sub, lld-circuit-breaker

-- LLD Intro
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'lld-intro';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'lld-intro', 'multiple-choice', 'easy', 'What is Low-Level Design (LLD)?', NULL, '["System architecture diagrams", "Detailed class/struct design for a component", "Database schema design", "UI/UX design"]', '1', 'LLD focuses on detailed design of classes, interfaces, and their interactions within a specific component.', 1),
('go-oop', 'lld-intro', 'multiple-choice', 'easy', 'What is the first step in LLD process?', NULL, '["Write code immediately", "Gather and clarify requirements", "Create database schema", "Choose programming language"]', '1', 'Always start by gathering requirements - functional (what it does) and non-functional (scalability, performance).', 2),
('go-oop', 'lld-intro', 'true-false', 'easy', 'In LLD interviews, you should start coding immediately to save time.', NULL, NULL, 'false', 'Clarify requirements first. Understanding the problem thoroughly leads to better design decisions.', 3),
('go-oop', 'lld-intro', 'multiple-choice', 'medium', 'What are functional requirements?', NULL, '["Performance metrics", "What the system should DO", "Hardware specifications", "Team organization"]', '1', 'Functional requirements define features and behaviors. Non-functional define quality (performance, scalability).', 4),
('go-oop', 'lld-intro', 'code-output', 'medium', 'What step follows requirement gathering?', NULL, '["Write tests", "Entity/interface identification", "Deployment", "Database setup"]', '1', 'After requirements, identify the key entities (nouns) and their relationships before designing interfaces.', 5),
('go-oop', 'lld-intro', 'multiple-choice', 'medium', 'What is entity identification?', NULL, '["Creating database tables", "Identifying the core types/structs in your system", "Finding bugs", "Writing documentation"]', '1', 'Identify nouns from requirements: User, Order, Payment become structs. Verbs become methods.', 6),
('go-oop', 'lld-intro', 'true-false', 'medium', 'Interfaces should be designed before concrete implementations in LLD.', NULL, NULL, 'true', 'Design interfaces first (contracts), then implement. This supports testing and flexibility.', 7),
('go-oop', 'lld-intro', 'multiple-choice', 'medium', 'Why use ASCII diagrams in LLD?', NULL, '["They look professional", "Quick visualization of relationships without special tools", "Required by Go", "For documentation only"]', '1', 'ASCII diagrams quickly communicate structure during design/interviews without needing drawing tools.', 8),
('go-oop', 'lld-intro', 'code-output', 'hard', 'Which design pattern is most relevant to LLD?', NULL, '["Only Singleton", "Multiple patterns depending on requirements", "None", "Factory only"]', '1', 'LLD uses various patterns: Factory for creation, Strategy for algorithms, Observer for events, etc.', 9),
('go-oop', 'lld-intro', 'multiple-choice', 'medium', 'What should you consider for concurrent access?', NULL, '["Ignore it", "Use sync.Mutex or channels for shared state", "Make everything global", "Use sleep()"]', '1', 'Protect shared state with mutexes or channels. Identify what state is shared and how to synchronize.', 10),
('go-oop', 'lld-intro', 'identify-bug', 'hard', 'What is missing from this LLD process?', 'Requirements -> Entity Design -> Implementation -> Done', '["Nothing missing", "Testing and validation step", "Database step", "UI step"]', '1', 'Testing should be part of design. Write test cases that verify requirements are met.', 11),
('go-oop', 'lld-intro', 'true-false', 'easy', 'LLD should consider extensibility for future requirements.', NULL, NULL, 'true', 'Good LLD follows OCP - design should be open for extension without modifying existing code.', 12),
('go-oop', 'lld-intro', 'multiple-choice', 'hard', 'How do you handle time complexity in LLD?', NULL, '["Ignore it", "Analyze and optimize critical paths", "Always use O(1) operations", "Use caching everywhere"]', '1', 'Identify hot paths and ensure acceptable complexity. Document trade-offs.', 13),
('go-oop', 'lld-intro', 'code-output', 'medium', 'What makes a good LLD interface?', NULL, '["Many methods for flexibility", "Small, focused interface following ISP", "No interface, use concrete types", "Generic interface{}"]', '1', 'Small interfaces are easier to implement, test, and extend. Follow Interface Segregation.', 14),
('go-oop', 'lld-intro', 'multiple-choice', 'medium', 'What is relationship mapping in LLD?', NULL, '["Database foreign keys only", "Defining how entities relate (has-a, uses)", "Network topology", "Team structure"]', '1', 'Map how entities interact: Cache has-a map, RateLimiter uses TokenBucket, etc.', 15);

-- LLD Cache
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'lld-cache';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'lld-cache', 'multiple-choice', 'easy', 'What is the main purpose of a cache?', NULL, '["Store permanent data", "Speed up access to frequently used data", "Replace databases", "Compress data"]', '1', 'Cache stores frequently accessed data in fast storage (memory) to reduce expensive operations (DB, network).', 1),
('go-oop', 'lld-cache', 'multiple-choice', 'easy', 'What does LRU stand for?', NULL, '["Last Recently Updated", "Least Recently Used", "Latest Running Update", "Long Range Usage"]', '1', 'LRU: Least Recently Used. Evict items that haven''t been accessed for the longest time.', 2),
('go-oop', 'lld-cache', 'code-output', 'medium', 'What data structures does LRU cache typically use?', NULL, '["Only array", "HashMap + Doubly Linked List", "Only linked list", "Binary tree"]', '1', 'HashMap for O(1) lookup, doubly linked list for O(1) removal and reordering of access order.', 3),
('go-oop', 'lld-cache', 'true-false', 'medium', 'LRU cache operations (Get, Put) should be O(1).', NULL, NULL, 'true', 'LRU cache provides O(1) Get and Put. HashMap gives O(1) lookup, linked list gives O(1) move/remove.', 4),
('go-oop', 'lld-cache', 'multiple-choice', 'medium', 'When should cache eviction happen?', NULL, '["Never", "When cache reaches capacity on Put", "Every minute", "On every Get"]', '1', 'Evict when adding new item would exceed capacity. Remove least recently used item.', 5),
('go-oop', 'lld-cache', 'code-output', 'hard', 'What happens on cache hit in LRU?', NULL, '["Nothing", "Move item to front (most recently used)", "Delete item", "Increment counter"]', '1', 'On cache hit, move the accessed item to front of list - it''s now most recently used.', 6),
('go-oop', 'lld-cache', 'identify-bug', 'hard', 'What is the concurrency issue?', 'type Cache struct {\n    data map[string]int\n}\nfunc (c *Cache) Get(k string) int { return c.data[k] }\nfunc (c *Cache) Put(k string, v int) { c.data[k] = v }', '["No issue", "Concurrent Get/Put on map causes race condition", "Missing capacity", "Wrong return type"]', '1', 'Go maps are not thread-safe. Concurrent reads and writes cause race conditions. Use sync.RWMutex.', 7),
('go-oop', 'lld-cache', 'multiple-choice', 'medium', 'Why does LRU cache use Lock() instead of RLock() for Get?', NULL, '["RLock is slower", "Get() modifies the list order by moving item to front", "Go maps require Lock()", "RLock doesn''t exist"]', '1', 'LRU Get() moves the accessed item to front of the list, which is a write operation. RLock() only works for true read-only operations.', 8),
('go-oop', 'lld-cache', 'code-output', 'medium', 'What is TTL in caching?', NULL, '["Total Transfer Length", "Time To Live - expiration time for entries", "Type To Load", "Transfer Token Length"]', '1', 'TTL: Time To Live. Entries expire after TTL, preventing stale data.', 9),
('go-oop', 'lld-cache', 'true-false', 'hard', 'Checking TTL on every Get is more accurate than background cleanup.', NULL, NULL, 'true', 'Checking TTL on Get ensures no stale data is returned. Background cleanup may have delays.', 10),
('go-oop', 'lld-cache', 'multiple-choice', 'hard', 'What is cache stampede?', NULL, '["Cache running fast", "Many requests for same expired key hit backend simultaneously", "Cache overflow", "Memory leak"]', '1', 'When a popular key expires, many requests simultaneously miss cache and hit backend. Use locking or probabilistic early expiration.', 11),
('go-oop', 'lld-cache', 'code-output', 'medium', 'Which eviction policy removes oldest inserted item?', NULL, '["LRU", "FIFO", "LFU", "Random"]', '1', 'FIFO: First In First Out. Evict oldest inserted regardless of access pattern.', 12),
('go-oop', 'lld-cache', 'multiple-choice', 'medium', 'What is LFU eviction?', NULL, '["Least Frequently Used", "Last First Updated", "Longest File Usage", "Latest Feature Update"]', '0', 'LFU: Least Frequently Used. Evict items with lowest access count. Good for stable access patterns.', 13),
('go-oop', 'lld-cache', 'identify-bug', 'hard', 'What could cause memory issues?', 'type Cache struct {\n    data map[string]*BigObject\n    // No capacity limit\n}', '["No issue", "Unbounded cache can consume all memory", "Should use interface{}", "Wrong pointer usage"]', '1', 'Cache without capacity limit grows unbounded. Always set max capacity and eviction policy.', 14),
('go-oop', 'lld-cache', 'true-false', 'medium', 'Cache should be transparent - callers shouldn''t know if data is cached.', NULL, NULL, 'true', 'Ideal cache is transparent. Same interface whether cached or not. This is why Cache implements same interface as underlying store.', 15);

-- LLD Rate Limiter
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'lld-rate-limiter';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'lld-rate-limiter', 'multiple-choice', 'easy', 'What is the purpose of rate limiting?', NULL, '["Speed up requests", "Control the rate of requests to protect resources", "Compress data", "Cache responses"]', '1', 'Rate limiting prevents abuse and protects services from being overwhelmed by too many requests.', 1),
('go-oop', 'lld-rate-limiter', 'multiple-choice', 'easy', 'What does Token Bucket algorithm use?', NULL, '["Queue of requests", "Bucket of tokens that refill over time", "Hash map", "Binary tree"]', '1', 'Token Bucket: bucket holds tokens, refilled at constant rate. Each request consumes a token.', 2),
('go-oop', 'lld-rate-limiter', 'code-output', 'medium', 'What happens when token bucket is empty?', NULL, '["Request succeeds anyway", "Request is rejected or queued", "System crashes", "Token is borrowed"]', '1', 'No tokens = request denied. Client must wait for bucket to refill or handle rejection.', 3),
('go-oop', 'lld-rate-limiter', 'true-false', 'medium', 'Token bucket allows short bursts above the average rate.', NULL, NULL, 'true', 'Token bucket allows bursts up to bucket capacity. Average rate is limited, but momentary spikes are ok.', 4),
('go-oop', 'lld-rate-limiter', 'multiple-choice', 'medium', 'What is Sliding Window algorithm?', NULL, '["Fixed time windows", "Rolling time window that slides with each request", "Token-based system", "Queue-based system"]', '1', 'Sliding window tracks requests in a rolling time period, smoother than fixed windows.', 5),
('go-oop', 'lld-rate-limiter', 'code-output', 'hard', 'What is the issue with fixed window rate limiting?', NULL, '["Too complex", "Boundary problem - bursts at window edges", "Too slow", "Uses too much memory"]', '1', 'Fixed window allows 2x limit at window boundaries (end of one window + start of next).', 6),
('go-oop', 'lld-rate-limiter', 'identify-bug', 'hard', 'What is the concurrency issue?', 'func (r *RateLimiter) Allow() bool {\n    if r.tokens > 0 {\n        r.tokens--\n        return true\n    }\n    return false\n}', '["No issue", "Race condition - check and decrement not atomic", "Wrong return type", "Missing refill"]', '1', 'Check-then-act is not atomic. Two goroutines could both see tokens > 0 and decrement. Use mutex.', 7),
('go-oop', 'lld-rate-limiter', 'multiple-choice', 'medium', 'How do you handle distributed rate limiting?', NULL, '["Local counters only", "Centralized store like Redis", "No solution exists", "Disable rate limiting"]', '1', 'Distributed systems need centralized counter (Redis) or gossip protocol for approximate limiting.', 8),
('go-oop', 'lld-rate-limiter', 'true-false', 'medium', 'Rate limiter should return how long until retry is allowed.', NULL, NULL, 'true', 'Good rate limiters return retry-after duration. Helps clients implement backoff without guessing.', 9),
('go-oop', 'lld-rate-limiter', 'code-output', 'medium', 'What identifies the client for rate limiting?', NULL, '["Nothing", "IP address, API key, or user ID", "Random assignment", "Server timestamp"]', '1', 'Rate limit per client identity: IP for anonymous, API key for authenticated, user ID for logged-in users.', 10),
('go-oop', 'lld-rate-limiter', 'multiple-choice', 'hard', 'What is Leaky Bucket algorithm?', NULL, '["Same as Token Bucket", "Requests queue and process at constant rate like water leaking", "Memory leak detection", "Bucket with holes"]', '1', 'Leaky Bucket: requests queue, processed at constant rate. Smooths out bursts (unlike Token Bucket).', 11),
('go-oop', 'lld-rate-limiter', 'code-output', 'medium', 'Token Bucket vs Leaky Bucket?', NULL, '["Same thing", "Token allows bursts, Leaky enforces constant rate", "Leaky allows bursts, Token enforces constant rate", "Neither allows bursts"]', '1', 'Token Bucket allows bursts up to bucket size. Leaky Bucket processes at constant rate, queuing excess.', 12),
('go-oop', 'lld-rate-limiter', 'multiple-choice', 'medium', 'What HTTP status code for rate limit exceeded?', NULL, '["400 Bad Request", "403 Forbidden", "429 Too Many Requests", "503 Service Unavailable"]', '2', '429 Too Many Requests is the standard code. Include Retry-After header.', 13),
('go-oop', 'lld-rate-limiter', 'identify-bug', 'hard', 'What is wrong with this refill logic?', 'func (r *RateLimiter) refill() {\n    r.tokens = r.maxTokens  // Called every second\n}', '["Nothing wrong", "Should add tokens incrementally, not reset to max", "Missing mutex", "Wrong type"]', '1', 'Resetting to max loses partial refills. Should add (elapsed * rate) capped at max.', 14),
('go-oop', 'lld-rate-limiter', 'true-false', 'hard', 'Sliding window counter is more memory-efficient than sliding window log.', NULL, NULL, 'true', 'Sliding window log stores each request timestamp. Counter stores only counts per sub-window. Counter uses less memory.', 15);

-- LLD Parking Lot
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'lld-parking-lot';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'lld-parking-lot', 'multiple-choice', 'easy', 'What are the main entities in a parking lot system?', NULL, '["Only cars", "ParkingLot, Floor, Spot, Vehicle, Ticket", "Database tables", "Users only"]', '1', 'Key entities: ParkingLot (has floors), Floor (has spots), Spot (holds vehicle), Vehicle (Car/Bike/Truck), Ticket.', 1),
('go-oop', 'lld-parking-lot', 'multiple-choice', 'easy', 'What should happen when a vehicle enters?', NULL, '["Just park anywhere", "Find available spot, allocate it, issue ticket", "No action needed", "Payment first"]', '1', 'Entry: check availability, find appropriate spot (by vehicle type), allocate spot, issue ticket with timestamp.', 2),
('go-oop', 'lld-parking-lot', 'true-false', 'medium', 'Different vehicle types (car, bike, truck) need different spot sizes.', NULL, NULL, 'true', 'Bike spots are smaller than car spots, trucks need large spots. Match vehicle type to appropriate spot.', 3),
('go-oop', 'lld-parking-lot', 'code-output', 'medium', 'What interface makes vehicles interchangeable?', 'type Vehicle interface {\n    GetType() VehicleType\n    GetLicensePlate() string\n}', '["Factory", "Strategy", "Polymorphism - different vehicles, same interface", "Observer"]', '2', 'Vehicle interface allows Car, Bike, Truck to be handled uniformly while having specific implementations.', 4),
('go-oop', 'lld-parking-lot', 'multiple-choice', 'medium', 'How do you find an available spot efficiently?', NULL, '["Linear search through all spots", "Maintain list/queue of available spots per type", "Random selection", "Binary search"]', '1', 'Maintain availability by type. When spot is freed, add to available queue. O(1) to find spot.', 5),
('go-oop', 'lld-parking-lot', 'identify-bug', 'hard', 'What is the concurrency issue?', 'func (p *ParkingLot) Park(v Vehicle) (*Spot, error) {\n    spot := p.findAvailableSpot(v.GetType())\n    if spot == nil { return nil, ErrFull }\n    spot.Vehicle = v\n    return spot, nil\n}', '["No issue", "Two vehicles could get same spot - not atomic", "Wrong return", "Missing ticket"]', '1', 'Find-then-assign is not atomic. Two goroutines could find same spot. Use mutex around the operation.', 6),
('go-oop', 'lld-parking-lot', 'multiple-choice', 'medium', 'What information should a parking ticket contain?', NULL, '["Just ticket ID", "Ticket ID, spot info, entry time, vehicle info", "Only price", "Only exit time"]', '1', 'Ticket needs: ID, spot location, entry timestamp, vehicle license plate for verification.', 7),
('go-oop', 'lld-parking-lot', 'code-output', 'medium', 'How is parking fee calculated?', NULL, '["Fixed price", "Based on duration: exit time - entry time", "By vehicle color", "Random"]', '1', 'Fee = (exit time - entry time) * rate per hour. Different rates for different vehicle types.', 8),
('go-oop', 'lld-parking-lot', 'true-false', 'easy', 'A parking spot should track whether it is occupied.', NULL, NULL, 'true', 'Spot needs isOccupied or Vehicle field. When Vehicle is nil/zero, spot is available.', 9),
('go-oop', 'lld-parking-lot', 'multiple-choice', 'hard', 'What pattern helps create different vehicle types?', NULL, '["Singleton", "Factory - create Car/Bike/Truck based on type", "Observer", "Decorator"]', '1', 'Factory pattern: NewVehicle(type, plate) returns appropriate Vehicle implementation.', 10),
('go-oop', 'lld-parking-lot', 'code-output', 'hard', 'How do you handle multiple floors?', NULL, '["One big list of spots", "Array of floors, each with array of spots", "Database only", "Ignore floors"]', '1', 'ParkingLot has []Floor, each Floor has []Spot. Can optimize spot finding by floor availability.', 11),
('go-oop', 'lld-parking-lot', 'identify-bug', 'medium', 'What is wrong with this exit flow?', 'func (p *ParkingLot) Exit(ticket *Ticket) error {\n    fee := p.calculateFee(ticket)\n    p.collectPayment(fee)\n    return nil\n}', '["Nothing wrong", "Should free the spot after exit", "Missing time", "Wrong error handling"]', '1', 'Must free the spot: spot.Vehicle = nil. Otherwise spot stays occupied forever.', 12),
('go-oop', 'lld-parking-lot', 'multiple-choice', 'medium', 'What is VehicleType typically implemented as?', NULL, '["String", "Enum/const (type VehicleType int)", "Interface", "Struct"]', '1', 'VehicleType as const enum: const (Car VehicleType = iota; Bike; Truck). Type-safe, comparable.', 13),
('go-oop', 'lld-parking-lot', 'true-false', 'hard', 'Parking lot should support reservations and real-time occupancy.', NULL, NULL, 'true', 'Advanced features: reserve spot in advance, display available count on entrance signs.', 14),
('go-oop', 'lld-parking-lot', 'code-output', 'medium', 'What should GetAvailableSpots return?', NULL, '["Total capacity", "Count of free spots, possibly by type", "List of all spots", "Nothing"]', '1', 'Return available count, ideally per vehicle type: AvailableSpots() map[VehicleType]int.', 15);

-- LLD Logger
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'lld-logger';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'lld-logger', 'multiple-choice', 'easy', 'What are common log levels?', NULL, '["Only ERROR", "DEBUG, INFO, WARN, ERROR, FATAL", "1, 2, 3, 4, 5", "LOW, MEDIUM, HIGH"]', '1', 'Standard levels: DEBUG (verbose), INFO (normal), WARN (potential issues), ERROR (failures), FATAL (critical).', 1),
('go-oop', 'lld-logger', 'multiple-choice', 'easy', 'What pattern allows multiple log outputs (file, console)?', NULL, '["Singleton", "Strategy or Observer", "Factory", "Builder"]', '1', 'Strategy for different formatters, Observer for multiple handlers. Log event goes to all registered handlers.', 2),
('go-oop', 'lld-logger', 'code-output', 'medium', 'What does this interface enable?', 'type Handler interface {\n    Handle(level Level, msg string)\n}', '["Single output", "Multiple handlers (file, console, network) with same interface", "Log parsing", "Compression"]', '1', 'Handler interface enables: FileHandler, ConsoleHandler, NetworkHandler - all interchangeable.', 3),
('go-oop', 'lld-logger', 'true-false', 'medium', 'Logger should filter messages below the configured level.', NULL, NULL, 'true', 'If level is INFO, DEBUG messages should not be output. Filter before formatting.', 4),
('go-oop', 'lld-logger', 'multiple-choice', 'medium', 'Why use structured logging (JSON) over plain text?', NULL, '["Prettier output", "Machine-parseable for log aggregation systems", "Smaller size", "Required by Go"]', '1', 'Structured logs (JSON) are easy to parse, search, and analyze with tools like ELK, Splunk.', 5),
('go-oop', 'lld-logger', 'code-output', 'hard', 'What is the thread-safety concern?', 'type Logger struct {\n    handlers []Handler\n    level    Level\n}\nfunc (l *Logger) Log(level Level, msg string) {\n    for _, h := range l.handlers {\n        h.Handle(level, msg)\n    }\n}', '["No concern", "Concurrent Log calls may race with AddHandler", "Wrong loop", "Missing level check"]', '1', 'If AddHandler modifies handlers slice while Log iterates, race condition occurs. Use RWMutex.', 6),
('go-oop', 'lld-logger', 'multiple-choice', 'medium', 'What is a Formatter in logging?', NULL, '["Log level filter", "Converts log data to output format (text, JSON)", "File rotator", "Network sender"]', '1', 'Formatter transforms log entry to string: TextFormatter, JSONFormatter. Separate from Handler (where to send).', 7),
('go-oop', 'lld-logger', 'identify-bug', 'hard', 'What could cause issues?', 'func (l *Logger) Fatal(msg string) {\n    l.Log(FATAL, msg)\n    os.Exit(1)\n}', '["Nothing wrong", "Deferred cleanup functions won''t run after os.Exit", "Wrong level", "Missing handler"]', '1', 'os.Exit() skips deferred functions. Consider: flush handlers, run cleanup before exit.', 8),
('go-oop', 'lld-logger', 'true-false', 'easy', 'Log rotation prevents log files from growing indefinitely.', NULL, NULL, 'true', 'Rotation: when file reaches size/age limit, archive it and start new file. Prevents disk fill.', 9),
('go-oop', 'lld-logger', 'multiple-choice', 'medium', 'What is the benefit of log context/fields?', NULL, '["Shorter messages", "Add structured metadata (user_id, request_id) to every log", "Faster logging", "Required for JSON"]', '1', 'Context fields add consistent metadata. Every log includes request_id without repeating in message.', 10),
('go-oop', 'lld-logger', 'code-output', 'medium', 'What does WithFields return?', 'logger.WithFields(Fields{"user_id": 123}).Info("user logged in")', '["Error", "New logger with added context fields", "Nothing", "String"]', '1', 'WithFields returns new logger that includes those fields in all subsequent logs. Immutable pattern.', 11),
('go-oop', 'lld-logger', 'multiple-choice', 'hard', 'How do you handle high-volume logging without blocking?', NULL, '["Log synchronously always", "Use buffered channel and background goroutine", "Drop logs", "Disable logging"]', '1', 'Buffer logs in channel, background goroutine writes. Non-blocking for main path. May drop under extreme load.', 12),
('go-oop', 'lld-logger', 'identify-bug', 'medium', 'What is missing?', 'type FileHandler struct {\n    file *os.File\n}\nfunc (h *FileHandler) Handle(level Level, msg string) {\n    h.file.WriteString(msg)\n}', '["Nothing", "Missing level filter, timestamp, and newline", "Wrong file type", "Too complex"]', '1', 'Should check level, add timestamp, and append newline. Also consider buffering and flush.', 13),
('go-oop', 'lld-logger', 'true-false', 'medium', 'Global logger is acceptable for simple applications.', NULL, NULL, 'true', 'For simple apps, global logger is pragmatic. For complex apps, inject logger as dependency.', 14),
('go-oop', 'lld-logger', 'code-output', 'hard', 'What does log sampling do?', NULL, '["Logs everything", "Logs only a percentage of events to reduce volume", "Improves log quality", "Adds timestamps"]', '1', 'Sampling: log only 1% of DEBUG events under high load. Reduces volume while capturing pattern.', 15);

-- LLD Pub/Sub
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'lld-pub-sub';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'lld-pub-sub', 'multiple-choice', 'easy', 'What is Pub/Sub pattern?', NULL, '["Database pattern", "Publishers send messages to topics, subscribers receive them", "File system pattern", "Network protocol"]', '1', 'Pub/Sub: decoupled messaging. Publishers don''t know subscribers. Messages go through topics/channels.', 1),
('go-oop', 'lld-pub-sub', 'multiple-choice', 'easy', 'What are the main components?', NULL, '["Only publishers", "Publisher, Subscriber, Topic/Channel, Broker", "Client and server", "Reader and writer"]', '1', 'Publisher sends to topic, Broker manages topics, Subscriber receives from topic.', 2),
('go-oop', 'lld-pub-sub', 'code-output', 'medium', 'What Go feature naturally fits Pub/Sub?', NULL, '["Interfaces", "Channels - built-in message passing", "Goroutines only", "Maps"]', '1', 'Go channels are perfect for Pub/Sub. Topic as channel, subscribers receive from it.', 3),
('go-oop', 'lld-pub-sub', 'true-false', 'medium', 'In Pub/Sub, publishers and subscribers are decoupled.', NULL, NULL, 'true', 'Publishers don''t know who subscribes. Subscribers don''t know who publishes. Broker connects them.', 4),
('go-oop', 'lld-pub-sub', 'identify-bug', 'hard', 'What is the issue?', 'func (t *Topic) Publish(msg Message) {\n    for _, sub := range t.subscribers {\n        sub.channel <- msg  // Blocking send\n    }\n}', '["No issue", "Slow subscriber blocks all subscribers and publisher", "Wrong channel direction", "Missing error"]', '1', 'Blocking send means one slow subscriber blocks everything. Use buffered channels or non-blocking select.', 5),
('go-oop', 'lld-pub-sub', 'multiple-choice', 'medium', 'How do you handle slow subscribers?', NULL, '["Block publisher", "Buffer messages, drop oldest on overflow", "Remove slow subscribers", "All options are valid strategies"]', '3', 'Options: buffer with overflow policy, drop messages, disconnect slow subscriber. Choose based on requirements.', 6),
('go-oop', 'lld-pub-sub', 'code-output', 'medium', 'What does Subscribe return?', 'func (b *Broker) Subscribe(topic string) <-chan Message', '["Error", "Receive-only channel for messages", "Send-only channel", "Topic object"]', '1', 'Subscribe returns receive-only channel. Subscriber reads messages, cannot send.', 7),
('go-oop', 'lld-pub-sub', 'multiple-choice', 'hard', 'How do you handle subscriber disconnection?', NULL, '["Ignore it", "Close their channel, handle panic, cleanup subscription", "Keep sending forever", "Restart subscriber"]', '1', 'Unsubscribe should close channel (signals subscriber), remove from subscriber list, prevent memory leak.', 8),
('go-oop', 'lld-pub-sub', 'true-false', 'medium', 'Each subscriber should have their own channel in Go Pub/Sub.', NULL, NULL, 'true', 'Each subscriber gets own channel. Publishing fans out message to all subscriber channels.', 9),
('go-oop', 'lld-pub-sub', 'code-output', 'hard', 'What prevents goroutine leak on unsubscribe?', 'func (b *Broker) Unsubscribe(topic string, subID string) {\n    ch := b.getChannel(subID)  // Get bidirectional channel\n    b.removeSubscriber(topic, subID)\n    close(ch)  // Signal subscriber goroutine to exit\n}', '["Nothing needed", "Close channel signals subscriber''s range loop to exit", "Use context", "Delete channel"]', '1', 'Closing channel breaks subscriber''s for msg := range ch loop, allowing goroutine to exit cleanly. Note: only the sender (broker) can close a channel.', 10),
('go-oop', 'lld-pub-sub', 'multiple-choice', 'medium', 'What is fan-out in Pub/Sub?', NULL, '["Publishing speed", "One message delivered to multiple subscribers", "Subscriber count", "Topic creation"]', '1', 'Fan-out: one published message goes to all subscribers on that topic.', 11),
('go-oop', 'lld-pub-sub', 'identify-bug', 'hard', 'What could cause deadlock?', 'func (b *Broker) Publish(topic string, msg Message) {\n    b.mu.Lock()\n    defer b.mu.Unlock()\n    for _, ch := range b.topics[topic] {\n        ch <- msg  // Send while holding lock\n    }\n}', '["No issue", "Blocking send while holding mutex - subscriber trying to unsubscribe deadlocks", "Wrong lock type", "Missing topic"]', '1', 'If subscriber''s channel is full and it tries to unsubscribe (needs lock), deadlock. Don''t hold lock during send.', 12),
('go-oop', 'lld-pub-sub', 'multiple-choice', 'medium', 'What is the purpose of message acknowledgment?', NULL, '["Politeness", "Confirm subscriber received/processed message for at-least-once delivery", "Speed up delivery", "Logging"]', '1', 'Acks enable reliable delivery. Without ack, message is redelivered. Important for exactly-once semantics.', 13),
('go-oop', 'lld-pub-sub', 'true-false', 'hard', 'Go channels provide at-most-once delivery by default.', NULL, NULL, 'true', 'Basic channel send is fire-and-forget. For at-least-once, need acks and retry. Exactly-once needs dedup.', 14),
('go-oop', 'lld-pub-sub', 'code-output', 'medium', 'What happens if publisher sends to closed channel?', NULL, '["Message is dropped", "Panic", "Message is buffered", "Error returned"]', '1', 'Sending to closed channel causes panic. Publisher must handle subscriber disconnection gracefully.', 15);

-- LLD Circuit Breaker
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'lld-circuit-breaker';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'lld-circuit-breaker', 'multiple-choice', 'easy', 'What is a circuit breaker pattern?', NULL, '["Electrical safety", "Prevents cascading failures by failing fast when service is down", "Load balancer", "Cache"]', '1', 'Circuit breaker stops calling failing service, returns error immediately. Prevents resource exhaustion.', 1),
('go-oop', 'lld-circuit-breaker', 'multiple-choice', 'easy', 'What are the three states of a circuit breaker?', NULL, '["On, Off, Standby", "Closed (normal), Open (failing), Half-Open (testing)", "Start, Running, Stopped", "Green, Yellow, Red"]', '1', 'Closed: requests pass through. Open: requests fail immediately. Half-Open: test if service recovered.', 2),
('go-oop', 'lld-circuit-breaker', 'code-output', 'medium', 'What triggers transition from Closed to Open?', NULL, '["First failure", "Failure count exceeds threshold", "Time passes", "Success occurs"]', '1', 'When failures exceed threshold (e.g., 5 failures in 10 seconds), circuit opens.', 3),
('go-oop', 'lld-circuit-breaker', 'true-false', 'medium', 'In Open state, all requests fail immediately without calling the service.', NULL, NULL, 'true', 'Open state: fail fast. No actual calls made. Protects the failing service from more load.', 4),
('go-oop', 'lld-circuit-breaker', 'multiple-choice', 'medium', 'What triggers transition from Open to Half-Open?', NULL, '["Success", "Timeout expires - time to test if service recovered", "Manual reset", "More failures"]', '1', 'After timeout in Open state, move to Half-Open to test if service recovered with limited requests.', 5),
('go-oop', 'lld-circuit-breaker', 'code-output', 'hard', 'What happens in Half-Open state?', NULL, '["All requests pass", "Limited test requests: all succeed = Close, any fail = Open", "Random behavior", "Error returned"]', '1', 'Half-Open allows limited test requests (e.g., 3). If all succeed, circuit closes. Any failure reopens it.', 6),
('go-oop', 'lld-circuit-breaker', 'identify-bug', 'hard', 'What is the concurrency issue?', 'func (cb *CircuitBreaker) Call(fn func() error) error {\n    if cb.state == Open {\n        return ErrCircuitOpen\n    }\n    err := fn()\n    if err != nil {\n        cb.failures++\n    }\n    return err\n}', '["No issue", "State check and failure increment not thread-safe", "Wrong state name", "Missing state transition"]', '1', 'Multiple goroutines: state check, failures increment all need mutex protection.', 7),
('go-oop', 'lld-circuit-breaker', 'multiple-choice', 'medium', 'Why is circuit breaker useful?', NULL, '["Faster code", "Prevents cascading failures, gives failing service time to recover", "Reduces code", "Required by HTTP"]', '1', 'Without circuit breaker, requests pile up waiting for timeout. Circuit breaker fails fast, protects resources.', 8),
('go-oop', 'lld-circuit-breaker', 'code-output', 'medium', 'What configuration does circuit breaker need?', NULL, '["Just threshold", "Threshold, timeout, half-open max requests", "Only timeout", "No configuration"]', '1', 'Config: failure threshold (trips breaker), timeout (Open duration), max half-open requests (test count).', 9),
('go-oop', 'lld-circuit-breaker', 'true-false', 'hard', 'Circuit breaker should reset failure count on success in Closed state.', NULL, NULL, 'true', 'Intermittent failures shouldn''t accumulate forever. Reset count on success or use sliding window.', 10),
('go-oop', 'lld-circuit-breaker', 'multiple-choice', 'hard', 'What is the sliding window approach?', NULL, '["Fixed failure count", "Track failures within time window, not total", "UI component", "Load balancing"]', '1', 'Sliding window: count failures in last N seconds. Old failures expire. More accurate than cumulative count.', 11),
('go-oop', 'lld-circuit-breaker', 'identify-bug', 'medium', 'What is missing?', 'func (cb *CircuitBreaker) Call(fn func() error) error {\n    if cb.state == Open && time.Since(cb.lastFailure) < cb.timeout {\n        return ErrCircuitOpen\n    }\n    return fn()\n}', '["Nothing", "Missing Half-Open state and transition to Closed on success", "Wrong timeout check", "Should panic"]', '1', 'After timeout, should enter Half-Open, not just allow calls. Need explicit state machine.', 12),
('go-oop', 'lld-circuit-breaker', 'true-false', 'medium', 'Circuit breaker can be combined with retry logic.', NULL, NULL, 'true', 'Retry within circuit breaker. If retries exhaust, circuit trips. Retry helps temporary failures.', 13),
('go-oop', 'lld-circuit-breaker', 'code-output', 'hard', 'What should Execute return when circuit is open?', NULL, '["nil", "Error indicating circuit is open + retry-after duration", "Panic", "Random value"]', '1', 'Return ErrCircuitOpen with metadata: when to retry. Helps callers implement backoff.', 14),
('go-oop', 'lld-circuit-breaker', 'multiple-choice', 'medium', 'What Go library implements circuit breaker?', NULL, '["Standard library", "github.com/sony/gobreaker", "database/sql", "net/http"]', '1', 'gobreaker is a popular Go circuit breaker. Also: hystrix-go. Not in standard library.', 15);
