-- Quiz Questions for Go OOP Part 2: OOP Philosophy
-- Sections: oop-intro, composition-patterns, functional-options, constructor-patterns

-- OOP Intro
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'oop-intro';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'oop-intro', 'multiple-choice', 'easy', 'Why doesn''t Go have classes?', NULL, '["It was an oversight", "Go uses structs + methods instead, favoring composition", "Classes are planned for Go 2", "Go is not object-oriented"]', '1', 'Go intentionally omits classes. Structs hold data, methods provide behavior, and composition replaces inheritance.', 1),
('go-oop', 'oop-intro', 'true-false', 'easy', 'Go supports inheritance through the extends keyword.', NULL, NULL, 'false', 'Go has no extends keyword. It uses composition (embedding) instead of inheritance.', 2),
('go-oop', 'oop-intro', 'multiple-choice', 'medium', 'What does "composition over inheritance" mean in Go?', NULL, '["Use interfaces instead of classes", "Build types by combining smaller types, not extending them", "Avoid using structs", "Always use generics"]', '1', 'Composition means building complex types by embedding simpler types, rather than inheriting from parent classes.', 3),
('go-oop', 'oop-intro', 'multiple-choice', 'medium', 'How does Go achieve polymorphism?', NULL, '["Through class hierarchies", "Through implicit interface satisfaction", "Through method overloading", "Through inheritance"]', '1', 'Go achieves polymorphism through interfaces. Any type with the right methods implements the interface implicitly.', 4),
('go-oop', 'oop-intro', 'multiple-choice', 'easy', 'What is the Go idiom for function parameters?', NULL, '["Accept concrete types for flexibility", "Accept interfaces, return concrete types", "Always use interface{}", "Use generics everywhere"]', '1', 'Accept interfaces for flexibility (callers can pass any implementation), return concrete types for clarity.', 5),
('go-oop', 'oop-intro', 'true-false', 'medium', 'In Go, you should define interfaces in the package that implements them.', NULL, NULL, 'false', 'Go convention: define interfaces where they are used (consumer), not where implemented. This keeps packages decoupled.', 6),
('go-oop', 'oop-intro', 'multiple-choice', 'medium', 'What is duck typing in Go?', NULL, '["A testing pattern", "If a type has the required methods, it implements the interface", "A way to handle nil pointers", "Dynamic typing at runtime"]', '1', 'Duck typing: if it walks like a duck and quacks like a duck, it''s a duck. If a type has the methods, it implements the interface.', 7),
('go-oop', 'oop-intro', 'multiple-choice', 'easy', 'Can a struct implement multiple interfaces?', NULL, '["No, only one interface per type", "Yes, if it has all required methods for each", "Only with explicit declarations", "Only pointer types can"]', '1', 'A type can implement any number of interfaces as long as it has all the required methods for each.', 8),
('go-oop', 'oop-intro', 'multiple-choice', 'hard', 'Why are small interfaces preferred in Go?', NULL, '["Performance reasons", "They are more reusable and easier to implement", "Go compiler limitation", "It is just a style preference"]', '1', 'Small interfaces (1-2 methods) are more reusable. io.Reader with just Read() is implemented by files, networks, buffers, etc.', 9),
('go-oop', 'oop-intro', 'true-false', 'medium', 'Go supports method overloading (same name, different parameters).', NULL, NULL, 'false', 'Go does not support method overloading. Each method name must be unique within a type.', 10),
('go-oop', 'oop-intro', 'multiple-choice', 'medium', 'How do you achieve encapsulation in Go?', NULL, '["Using private keyword", "Using protected keyword", "Lowercase names are package-private, uppercase are exported", "Go does not support encapsulation"]', '2', 'Go uses naming conventions: lowercase = unexported (package-private), uppercase = exported (public).', 11),
('go-oop', 'oop-intro', 'code-output', 'medium', 'What is the zero value of an interface?', NULL, '["Empty interface{}", "nil", "Undefined", "Panic"]', '1', 'The zero value of an interface is nil (both type and value are nil).', 12),
('go-oop', 'oop-intro', 'multiple-choice', 'hard', 'When is embedding NOT a good choice?', NULL, '["When you only want some methods, not all promoted", "When you need code reuse from another type", "When you want to implement an interface automatically", "When the embedded type has useful methods"]', '0', 'Embedding promotes ALL fields and methods. Use a named field when you want controlled access to only some of them.', 13),
('go-oop', 'oop-intro', 'identify-bug', 'hard', 'What is the problem with this design?', 'type UserService interface {\n    Create(u User) error\n    Update(u User) error\n    Delete(id string) error\n    Get(id string) (User, error)\n    List() ([]User, error)\n    SendEmail(u User) error\n    ValidatePassword(p string) bool\n}', '["Nothing wrong", "Interface is too large; violates ISP", "Methods should return pointers", "Missing context parameter"]', '1', 'This interface does too much (CRUD + email + validation). Split into smaller, focused interfaces.', 14),
('go-oop', 'oop-intro', 'multiple-choice', 'medium', 'What is the benefit of implicit interface satisfaction?', NULL, '["Faster compilation", "Types can satisfy interfaces without importing them", "Better error messages", "Required for generics"]', '1', 'Implicit satisfaction means a type in package A can implement an interface in package B without A importing B.', 15);

-- Composition Patterns
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'composition-patterns';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'composition-patterns', 'multiple-choice', 'easy', 'What happens to embedded struct fields?', NULL, '["They are hidden", "They are promoted to the outer struct", "They are copied", "They become methods"]', '1', 'Embedded struct fields are promoted, meaning you can access them directly on the outer struct.', 1),
('go-oop', 'composition-patterns', 'code-output', 'medium', 'What is printed?', 'type Logger struct { prefix string }\nfunc (l Logger) Log(msg string) { fmt.Println(l.prefix + msg) }\n\ntype App struct {\n    Logger\n    name string\n}\n\nfunc main() {\n    app := App{Logger: Logger{prefix: "[APP] "}, name: "MyApp"}\n    app.Log("started")\n}', '["[APP] started", "started", "MyApp started", "compile error"]', '0', 'The embedded Logger''s Log method is promoted. app.Log() calls Logger.Log() with the embedded prefix.', 2),
('go-oop', 'composition-patterns', 'true-false', 'medium', 'Embedding a pointer allows the embedded value to be nil.', NULL, NULL, 'true', 'When you embed a pointer type, it can be nil. This is useful for optional composition.', 3),
('go-oop', 'composition-patterns', 'code-output', 'hard', 'What happens here?', 'type Base struct{}\nfunc (b *Base) Init() { fmt.Println("Base.Init") }\n\ntype Child struct { Base }\nfunc (c *Child) Init() { fmt.Println("Child.Init") }\n\nfunc main() {\n    c := &Child{}\n    c.Init()\n    c.Base.Init()\n}', '["Child.Init then Base.Init", "Base.Init twice", "Child.Init twice", "compile error"]', '0', 'c.Init() calls Child''s shadowed method. c.Base.Init() explicitly calls the embedded Base''s method.', 4),
('go-oop', 'composition-patterns', 'multiple-choice', 'medium', 'How do you initialize an embedded struct?', NULL, '["Using the field name which is the type name", "Cannot initialize embedded structs", "Using super()", "Using init()"]', '0', 'The embedded field name is the type name. Initialize as: Outer{Inner: Inner{field: value}}.', 5),
('go-oop', 'composition-patterns', 'identify-bug', 'hard', 'What could go wrong?', 'type Metrics struct{}\nfunc (m *Metrics) Record() { /* uses m fields */ }\n\ntype Server struct {\n    *Metrics\n}', '["Nothing wrong", "Calling Record() on zero Server panics (nil pointer)", "Metrics should not be a pointer", "Missing constructor"]', '1', 'Embedding a pointer that is nil will panic when methods access the receiver. Initialize the embedded pointer.', 6),
('go-oop', 'composition-patterns', 'code-output', 'medium', 'Does Server implement Handler?', 'type Handler interface { Handle() }\ntype Router struct{}\nfunc (r Router) Handle() { }\n\ntype Server struct { Router }', '["Yes, Router''s Handle is promoted", "No, Server needs its own Handle", "Only *Server implements Handler", "Compile error"]', '0', 'Embedded methods are promoted to the outer type. Server has Handle() via Router, so it implements Handler.', 7),
('go-oop', 'composition-patterns', 'multiple-choice', 'medium', 'What is the difference between embedding and named field?', NULL, '["No difference", "Embedding promotes fields/methods, named field does not", "Named fields are faster", "Embedding is deprecated"]', '1', 'Embedding promotes access (outer.Field), named field requires explicit access (outer.inner.Field).', 8),
('go-oop', 'composition-patterns', 'true-false', 'hard', 'You can embed the same type multiple times in one struct.', NULL, NULL, 'false', 'You cannot embed the same type twice. Each embedded type name must be unique (it becomes the field name).', 9),
('go-oop', 'composition-patterns', 'code-output', 'medium', 'What type is c.Field?', 'type A struct { Field int }\ntype B struct { Field string }\ntype C struct { A; B }', '["int", "string", "Ambiguous - compile error", "interface{}"]', '2', 'When two embedded types have the same field name, accessing it is ambiguous and causes a compile error.', 10),
('go-oop', 'composition-patterns', 'multiple-choice', 'easy', 'Embedding is Go''s way of achieving what OOP concept?', NULL, '["Inheritance", "Encapsulation", "Composition and code reuse", "Polymorphism"]', '2', 'Embedding provides composition - combining types to reuse their fields and methods without inheritance.', 11),
('go-oop', 'composition-patterns', 'code-output', 'medium', 'Can you access the embedded type directly?', 'type Inner struct { value int }\ntype Outer struct { Inner }\n\nfunc main() {\n    o := Outer{Inner{42}}\n    fmt.Println(o.Inner.value)\n}', '["42", "compile error", "0", "panic"]', '0', 'Yes, the embedded type is accessible by its type name: o.Inner gives you the embedded Inner struct.', 12),
('go-oop', 'composition-patterns', 'multiple-choice', 'hard', 'When embedding interfaces, what happens?', NULL, '["Compile error", "The outer type must implement the interface", "The outer type gains the interface''s method set", "Nothing special"]', '2', 'Embedding an interface adds those method signatures to the outer type''s method set. The outer type must provide implementations.', 13),
('go-oop', 'composition-patterns', 'true-false', 'medium', 'Promoted methods can be overridden by defining the same method on the outer type.', NULL, NULL, 'true', 'If the outer type defines a method with the same name, it shadows the promoted method. Both remain accessible.', 14),
('go-oop', 'composition-patterns', 'multiple-choice', 'medium', 'What is a common use case for embedding interfaces in structs?', NULL, '["To avoid implementing all methods", "For partial implementation or decoration", "To create abstract classes", "For performance"]', '1', 'Embedding an interface in a struct lets you selectively override methods while delegating others to an inner implementation.', 15);

-- Functional Options
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'functional-options';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'functional-options', 'multiple-choice', 'easy', 'What problem do functional options solve?', NULL, '["Memory allocation", "Functions with many optional parameters", "Concurrency issues", "Type safety"]', '1', 'Functional options provide a clean API for functions with many optional parameters without boolean flags or config structs.', 1),
('go-oop', 'functional-options', 'code-output', 'medium', 'What type is an option function?', 'type Option func(*Config)\n\nfunc WithTimeout(d time.Duration) Option {\n    return func(c *Config) {\n        c.Timeout = d\n    }\n}', '["func(*Config)", "func(Config)", "*Config", "Option"]', '0', 'An option is a function that modifies the config. WithTimeout returns such a function.', 2),
('go-oop', 'functional-options', 'code-output', 'medium', 'How are options applied?', 'func NewServer(opts ...Option) *Server {\n    cfg := defaultConfig()\n    for _, opt := range opts {\n        opt(&cfg)\n    }\n    return &Server{cfg: cfg}\n}', '["Options modify the config in a loop", "Options are stored for later", "Options return new configs", "Options are ignored"]', '0', 'Each option function is called with a pointer to the config, allowing it to modify specific fields.', 3),
('go-oop', 'functional-options', 'true-false', 'easy', 'Functional options can only be used with structs.', NULL, NULL, 'false', 'Functional options can configure any type. They are commonly used with structs but work with any configuration target.', 4),
('go-oop', 'functional-options', 'multiple-choice', 'medium', 'What is an advantage of functional options over a config struct?', NULL, '["Faster execution", "Options can validate and return errors", "Less memory usage", "Simpler implementation"]', '1', 'Options can include validation logic and return errors, which plain struct fields cannot do.', 5),
('go-oop', 'functional-options', 'code-output', 'hard', 'What does this option do?', 'func WithLogger(l Logger) Option {\n    return func(c *Config) {\n        if l != nil {\n            c.Logger = l\n        }\n    }\n}', '["Sets logger unconditionally", "Sets logger only if not nil", "Returns an error if nil", "Creates a new logger"]', '1', 'This option validates the input - it only sets the logger if a non-nil value is provided.', 6),
('go-oop', 'functional-options', 'multiple-choice', 'medium', 'What is the typical signature for an option with validation?', NULL, '["func(*Config)", "func(*Config) error", "func(Config)", "func() *Config"]', '1', 'When validation is needed, options return error: type Option func(*Config) error.', 7),
('go-oop', 'functional-options', 'code-output', 'easy', 'How do you call a function with functional options?', NULL, '["NewServer(WithTimeout(5*time.Second), WithPort(8080))", "NewServer({Timeout: 5*time.Second})", "NewServer().WithTimeout(5)", "NewServer(timeout=5)"]', '0', 'Options are passed as variadic arguments. Each With* function returns an Option.', 8),
('go-oop', 'functional-options', 'true-false', 'medium', 'Functional options allow zero-configuration defaults.', NULL, NULL, 'true', 'You can call NewServer() with no options and get sensible defaults. Options only override what you specify.', 9),
('go-oop', 'functional-options', 'multiple-choice', 'hard', 'Which popular Go library uses functional options?', NULL, '["fmt", "net/http", "encoding/json", "google.golang.org/grpc"]', '3', 'gRPC''s grpc.Dial uses functional options extensively. Many popular Go libraries adopted this pattern.', 10),
('go-oop', 'functional-options', 'identify-bug', 'hard', 'What is wrong with this option?', 'func WithSize(size int) Option {\n    return func(c *Config) {\n        c.Size = size\n    }\n}', '["Nothing wrong", "Should validate size > 0", "Should use pointer receiver", "Missing error return"]', '1', 'Options should validate input. Negative size could cause issues. Add: if size <= 0 { return } or return error.', 11),
('go-oop', 'functional-options', 'code-output', 'medium', 'Can you combine multiple options into one?', 'func WithDefaults() Option {\n    return func(c *Config) {\n        WithTimeout(30*time.Second)(c)\n        WithRetries(3)(c)\n    }\n}', '["Yes, options can call other options", "No, options must be independent", "Compile error", "Runtime panic"]', '0', 'Options can compose other options, creating convenient presets like WithDefaults() or WithProduction().', 12),
('go-oop', 'functional-options', 'multiple-choice', 'medium', 'What is the naming convention for option functions?', NULL, '["Set*", "With*", "Option*", "Configure*"]', '1', 'Go convention is With* for option functions: WithTimeout, WithLogger, WithRetries, etc.', 13),
('go-oop', 'functional-options', 'true-false', 'easy', 'Functional options are applied in the order they are passed.', NULL, NULL, 'true', 'Options are applied sequentially. Later options can override earlier ones.', 14),
('go-oop', 'functional-options', 'multiple-choice', 'medium', 'When should you prefer a config struct over functional options?', NULL, '["When you have 2-3 required parameters", "When all parameters are required with no defaults", "When options need validation", "When building public APIs"]', '1', 'Use a config struct when most fields are required. Functional options shine with many optional parameters.', 15);

-- Constructor Patterns
DELETE FROM quiz_questions WHERE pattern_id = 'go-oop' AND section_slug = 'constructor-patterns';
INSERT INTO quiz_questions (pattern_id, section_slug, question_type, difficulty, question_text, code_snippet, options, correct_answer, explanation, display_order) VALUES
('go-oop', 'constructor-patterns', 'multiple-choice', 'easy', 'What is the Go naming convention for constructors?', NULL, '["Create*()", "New*()", "Make*()", "Init*()"]', '1', 'Go convention is New* for constructor functions: NewServer(), NewClient(), NewConfig().', 1),
('go-oop', 'constructor-patterns', 'code-output', 'easy', 'What should NewUser return?', 'func NewUser(name string) ??? {\n    return &User{Name: name, CreatedAt: time.Now()}\n}', '["User", "*User", "interface{}", "error"]', '1', 'Constructors that use & return pointers. NewUser returns *User since it creates with &User{}.', 2),
('go-oop', 'constructor-patterns', 'true-false', 'easy', 'Go has a built-in constructor mechanism like __init__ in Python.', NULL, NULL, 'false', 'Go has no built-in constructors. Convention is to write New* functions that return initialized values.', 3),
('go-oop', 'constructor-patterns', 'code-output', 'medium', 'What is the idiomatic return type?', 'func NewConfig(path string) ??? {\n    data, err := os.ReadFile(path)\n    if err != nil {\n        return nil, err\n    }\n    // parse and return\n}', '["*Config", "(*Config, error)", "Config", "(Config, error)"]', '1', 'When a constructor can fail, return (*Type, error). This is the idiomatic Go error handling pattern.', 4),
('go-oop', 'constructor-patterns', 'multiple-choice', 'medium', 'What is a factory function?', NULL, '["A function that returns interfaces based on input", "A function that returns only structs", "A function with no parameters", "A method on a struct"]', '0', 'Factory functions return different implementations (often interfaces) based on input parameters.', 5),
('go-oop', 'constructor-patterns', 'code-output', 'medium', 'What pattern is this?', 'func NewLogger(logType string) Logger {\n    switch logType {\n    case "file":\n        return &FileLogger{}\n    case "console":\n        return &ConsoleLogger{}\n    default:\n        return &NullLogger{}\n    }\n}', '["Constructor", "Factory", "Builder", "Singleton"]', '1', 'This is a factory pattern - it returns different implementations of the Logger interface based on input.', 6),
('go-oop', 'constructor-patterns', 'multiple-choice', 'medium', 'When should you return a pointer from a constructor?', NULL, '["Always", "When the type has pointer receiver methods or is large", "Never", "Only for interfaces"]', '1', 'Return pointers when: methods use pointer receivers, struct is large, or you want to allow nil.', 7),
('go-oop', 'constructor-patterns', 'code-output', 'hard', 'What pattern enables this?', 'server := NewServer().\n    WithPort(8080).\n    WithTimeout(30*time.Second).\n    WithLogger(logger).\n    Build()', '["Factory", "Builder", "Singleton", "Constructor"]', '1', 'Builder pattern: method chaining for step-by-step construction, ending with Build() or similar.', 8),
('go-oop', 'constructor-patterns', 'identify-bug', 'medium', 'What is missing?', 'func NewDB(dsn string) *DB {\n    db, err := sql.Open("postgres", dsn)\n    if err != nil {\n        log.Fatal(err)\n    }\n    return &DB{conn: db}\n}', '["Nothing missing", "Should return error instead of calling log.Fatal", "Should use panic", "Should return interface"]', '1', 'Constructors should return errors, not call log.Fatal. Let callers decide how to handle failures.', 9),
('go-oop', 'constructor-patterns', 'true-false', 'medium', 'Builder pattern always requires a separate Builder type.', NULL, NULL, 'false', 'In Go, you can implement builder on the type itself using method chaining that returns *Type.', 10),
('go-oop', 'constructor-patterns', 'code-output', 'medium', 'What does this constructor validate?', 'func NewEmail(addr string) (*Email, error) {\n    if !strings.Contains(addr, "@") {\n        return nil, errors.New("invalid email")\n    }\n    return &Email{Address: addr}, nil\n}', '["Nothing", "Email contains @ symbol", "Email is not empty", "Email domain exists"]', '1', 'This constructor validates that the email address contains @. Constructors often validate invariants.', 11),
('go-oop', 'constructor-patterns', 'multiple-choice', 'hard', 'What is the MustNew convention?', NULL, '["Constructor that never fails", "Constructor that panics on error instead of returning it", "Constructor for must-have features", "Deprecated pattern"]', '1', 'MustNew* functions panic on error. Used when failure is a programming error, like regexp.MustCompile().', 12),
('go-oop', 'constructor-patterns', 'code-output', 'easy', 'When is MustNew appropriate?', NULL, '["For user input validation", "For compile-time known values like regex patterns", "For network connections", "For file operations"]', '1', 'MustNew is for values known at compile time where failure indicates a bug, not runtime conditions.', 13),
('go-oop', 'constructor-patterns', 'multiple-choice', 'medium', 'How do you combine constructor with functional options?', NULL, '["func New(opts ...Option) *Type", "func New(cfg Config) *Type", "func New() *Type", "Not possible"]', '0', 'Combine variadic options: func NewServer(opts ...Option) *Server applies each option to defaults.', 14),
('go-oop', 'constructor-patterns', 'true-false', 'easy', 'Constructors should initialize all fields to valid states.', NULL, NULL, 'true', 'Constructors establish invariants. The returned value should be in a valid, usable state.', 15);
