import { Question } from "@/types";

export const questions: Question[] = [
  {
    id: "as-1",
    name: "Two Sum",
    url: "https://leetcode.com/problems/two-sum",
    difficulty: "Easy",
    pattern: "Hash Map",
    companies: [
      "Google",
      "Amazon",
      "Meta",
      "Apple",
      "Microsoft",
      "Netflix",
      "LinkedIn",
      "Tesla",
      "Databricks",
    ],
    frequency: "🔥🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-2",
    name: "3Sum",
    url: "https://leetcode.com/problems/3sum",
    difficulty: "Medium",
    pattern: "Two Pointers",
    companies: ["Google", "Amazon", "Apple", "Meta", "Tesla"],
    frequency: "🔥🔥🔥",
    category: "Two Pointers",
  },
  {
    id: "as-3",
    name: "Product of Array Except Self",
    url: "https://leetcode.com/problems/product-of-array-except-self",
    difficulty: "Medium",
    pattern: "Prefix/Suffix",
    companies: ["Google", "Amazon", "Meta", "Apple"],
    frequency: "🔥🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-4",
    name: "Maximum Subarray",
    url: "https://leetcode.com/problems/maximum-subarray",
    difficulty: "Medium",
    pattern: "Kadane's/DP",
    companies: ["Amazon", "Microsoft", "LinkedIn", "Tesla"],
    frequency: "🔥🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-5",
    name: "Group Anagrams",
    url: "https://leetcode.com/problems/group-anagrams",
    difficulty: "Medium",
    pattern: "Hash Map",
    companies: [
      "Google",
      "Amazon",
      "Meta",
      "Apple",
      "Tesla",
      "Salesforce",
      "Adobe",
    ],
    frequency: "🔥🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-6",
    name: "Valid Anagram",
    url: "https://leetcode.com/problems/valid-anagram",
    difficulty: "Easy",
    pattern: "Hash Map",
    companies: ["Amazon", "Google"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-7",
    name: "Contains Duplicate",
    url: "https://leetcode.com/problems/contains-duplicate",
    difficulty: "Easy",
    pattern: "Hash Set",
    companies: ["Amazon", "Google"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-8",
    name: "Valid Palindrome",
    url: "https://leetcode.com/problems/valid-palindrome",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Meta", "Amazon"],
    frequency: "🔥🔥",
    category: "Two Pointers",
  },
  {
    id: "as-9",
    name: "Valid Palindrome II",
    url: "https://leetcode.com/problems/valid-palindrome-ii",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Two Pointers",
  },
  {
    id: "as-10",
    name: "Move Zeroes",
    url: "https://leetcode.com/problems/move-zeroes",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Two Pointers",
  },
  {
    id: "as-11",
    name: "Rotate Image",
    url: "https://leetcode.com/problems/rotate-image",
    difficulty: "Medium",
    pattern: "Matrix",
    companies: ["Amazon", "Microsoft", "Google"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-12",
    name: "Sort Colors",
    url: "https://leetcode.com/problems/sort-colors",
    difficulty: "Medium",
    pattern: "Dutch Flag",
    companies: ["Microsoft", "Google"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-13",
    name: "String Compression",
    url: "https://leetcode.com/problems/string-compression",
    difficulty: "Medium",
    pattern: "Two Pointers",
    companies: ["Google"],
    frequency: "🔥",
    category: "Two Pointers",
  },
  {
    id: "as-14",
    name: "Encode and Decode Strings",
    url: "https://leetcode.com/problems/encode-and-decode-strings",
    difficulty: "Medium",
    pattern: "String",
    companies: ["Google"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-15",
    name: "Longest Common Prefix",
    url: "https://leetcode.com/problems/longest-common-prefix",
    difficulty: "Easy",
    pattern: "String",
    companies: ["Amazon"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-16",
    name: "Add Strings",
    url: "https://leetcode.com/problems/add-strings",
    difficulty: "Easy",
    pattern: "Math",
    companies: ["Meta", "Google"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-17",
    name: "Add Binary",
    url: "https://leetcode.com/problems/add-binary",
    difficulty: "Easy",
    pattern: "Math",
    companies: ["Google"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-18",
    name: "Merge Strings Alternately",
    url: "https://leetcode.com/problems/merge-strings-alternately",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Google"],
    frequency: "🔥",
    category: "Two Pointers",
  },
  {
    id: "as-19",
    name: "Integer to English Words",
    url: "https://leetcode.com/problems/integer-to-english-words",
    difficulty: "Hard",
    pattern: "String/Math",
    companies: ["Amazon", "Palantir"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-20",
    name: "First Missing Positive",
    url: "https://leetcode.com/problems/first-missing-positive",
    difficulty: "Hard",
    pattern: "Cyclic Sort",
    companies: ["Google", "Tesla"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-21",
    name: "Trapping Rain Water",
    url: "https://leetcode.com/problems/trapping-rain-water",
    difficulty: "Hard",
    pattern: "Two Pointers/Stack",
    companies: [
      "Google",
      "Amazon",
      "Apple",
      "Netflix",
      "Palantir",
      "Databricks",
    ],
    frequency: "🔥🔥🔥",
    category: "Two Pointers",
  },
  {
    id: "as-22",
    name: "Custom Sort String",
    url: "https://leetcode.com/problems/custom-sort-string",
    difficulty: "Medium",
    pattern: "Hash Map",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-23",
    name: "Maximum Swap",
    url: "https://leetcode.com/problems/maximum-swap",
    difficulty: "Medium",
    pattern: "Greedy",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-24",
    name: "Reverse Integer",
    url: "https://leetcode.com/problems/reverse-integer",
    difficulty: "Medium",
    pattern: "Math",
    companies: ["Amazon"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-25",
    name: "Find the Difference",
    url: "https://leetcode.com/problems/find-the-difference",
    difficulty: "Easy",
    pattern: "Hash/XOR",
    companies: ["Google"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-26",
    name: "Greatest Common Divisor of Strings",
    url: "https://leetcode.com/problems/greatest-common-divisor-of-strings",
    difficulty: "Easy",
    pattern: "Math/String",
    companies: ["Google", "Amazon"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-27",
    name: "Kids With the Greatest Number of Candies",
    url: "https://leetcode.com/problems/kids-with-the-greatest-number-of-candies",
    difficulty: "Easy",
    pattern: "Array",
    companies: ["Amazon"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-28",
    name: "Can Place Flowers",
    url: "https://leetcode.com/problems/can-place-flowers",
    difficulty: "Easy",
    pattern: "Greedy",
    companies: ["LinkedIn", "Amazon"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "as-29",
    name: "Reverse Vowels of a String",
    url: "https://leetcode.com/problems/reverse-vowels-of-a-string",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Google"],
    frequency: "🔥",
    category: "Two Pointers",
  },
  {
    id: "as-30",
    name: "Increasing Triplet Subsequence",
    url: "https://leetcode.com/problems/increasing-triplet-subsequence",
    difficulty: "Medium",
    pattern: "Greedy",
    companies: ["Meta", "Google"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },

  {
    id: "tp-1",
    name: "Container With Most Water",
    url: "https://leetcode.com/problems/container-with-most-water",
    difficulty: "Medium",
    pattern: "Two Pointers",
    companies: ["Google", "Amazon", "Apple"],
    frequency: "🔥🔥🔥",
    category: "Two Pointers",
  },
  {
    id: "tp-2",
    name: "Two Sum II - Input Array Is Sorted",
    url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted",
    difficulty: "Medium",
    pattern: "Two Pointers",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Two Pointers",
  },
  {
    id: "tp-3",
    name: "Remove Nth Node From End of List",
    url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list",
    difficulty: "Medium",
    pattern: "Fast/Slow",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Two Pointers",
  },
  {
    id: "tp-4",
    name: "Backspace String Compare",
    url: "https://leetcode.com/problems/backspace-string-compare",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Google"],
    frequency: "🔥",
    category: "Two Pointers",
  },
  {
    id: "tp-5",
    name: "Is Subsequence",
    url: "https://leetcode.com/problems/is-subsequence",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Google"],
    frequency: "🔥",
    category: "Two Pointers",
  },

  {
    id: "sw-1",
    name: "Longest Substring Without Repeating Characters",
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters",
    difficulty: "Medium",
    pattern: "Sliding Window",
    companies: ["Google", "Amazon", "Apple", "Microsoft", "Meta"],
    frequency: "🔥🔥🔥",
    category: "Sliding Window",
  },
  {
    id: "sw-2",
    name: "Minimum Window Substring",
    url: "https://leetcode.com/problems/minimum-window-substring",
    difficulty: "Hard",
    pattern: "Sliding Window",
    companies: ["Google", "Amazon", "Netflix", "Tesla"],
    frequency: "🔥🔥🔥",
    category: "Sliding Window",
  },
  {
    id: "sw-3",
    name: "Sliding Window Maximum",
    url: "https://leetcode.com/problems/sliding-window-maximum",
    difficulty: "Hard",
    pattern: "Monotonic Deque",
    companies: ["Google", "Amazon", "Uber"],
    frequency: "🔥🔥🔥",
    category: "Sliding Window",
  },
  {
    id: "sw-4",
    name: "Longest Repeating Character Replacement",
    url: "https://leetcode.com/problems/longest-repeating-character-replacement",
    difficulty: "Medium",
    pattern: "Sliding Window",
    companies: ["Amazon", "Apple"],
    frequency: "🔥🔥",
    category: "Sliding Window",
  },
  {
    id: "sw-5",
    name: "Maximum Average Subarray I",
    url: "https://leetcode.com/problems/maximum-average-subarray-i",
    difficulty: "Easy",
    pattern: "Sliding Window",
    companies: ["Google"],
    frequency: "🔥",
    category: "Sliding Window",
  },
  {
    id: "sw-6",
    name: "Max Consecutive Ones III",
    url: "https://leetcode.com/problems/max-consecutive-ones-iii",
    difficulty: "Medium",
    pattern: "Sliding Window",
    companies: ["Google"],
    frequency: "🔥",
    category: "Sliding Window",
  },
  {
    id: "sw-7",
    name: "Minimum Size Subarray Sum",
    url: "https://leetcode.com/problems/minimum-size-subarray-sum",
    difficulty: "Medium",
    pattern: "Sliding Window",
    companies: ["Google"],
    frequency: "🔥",
    category: "Sliding Window",
  },
  {
    id: "sw-8",
    name: "Find All Anagrams in a String",
    url: "https://leetcode.com/problems/find-all-anagrams-in-a-string",
    difficulty: "Medium",
    pattern: "Sliding Window",
    companies: ["Google", "Databricks"],
    frequency: "🔥🔥",
    category: "Sliding Window",
  },
  {
    id: "sw-9",
    name: "Permutation in String",
    url: "https://leetcode.com/problems/permutation-in-string",
    difficulty: "Medium",
    pattern: "Sliding Window",
    companies: ["Microsoft"],
    frequency: "🔥🔥",
    category: "Sliding Window",
  },
  {
    id: "sw-10",
    name: "Maximum Points You Can Obtain from Cards",
    url: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards",
    difficulty: "Medium",
    pattern: "Sliding Window",
    companies: ["Google"],
    frequency: "🔥",
    category: "Sliding Window",
  },

  {
    id: "ps-1",
    name: "Subarray Sum Equals K",
    url: "https://leetcode.com/problems/subarray-sum-equals-k",
    difficulty: "Medium",
    pattern: "Prefix Sum + Hash",
    companies: ["Meta", "Amazon", "Tesla"],
    frequency: "🔥🔥🔥",
    category: "Prefix Sum",
  },
  {
    id: "ps-2",
    name: "Continuous Subarray Sum",
    url: "https://leetcode.com/problems/continuous-subarray-sum",
    difficulty: "Medium",
    pattern: "Prefix Sum",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Prefix Sum",
  },
  {
    id: "ps-3",
    name: "Range Sum Query - Immutable",
    url: "https://leetcode.com/problems/range-sum-query-immutable",
    difficulty: "Easy",
    pattern: "Prefix Sum",
    companies: ["Google"],
    frequency: "🔥",
    category: "Prefix Sum",
  },
  {
    id: "ps-4",
    name: "Contiguous Array",
    url: "https://leetcode.com/problems/contiguous-array",
    difficulty: "Medium",
    pattern: "Prefix Sum",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Prefix Sum",
  },
  {
    id: "ps-5",
    name: "Find Pivot Index",
    url: "https://leetcode.com/problems/find-pivot-index",
    difficulty: "Easy",
    pattern: "Prefix Sum",
    companies: ["Google", "Tesla"],
    frequency: "🔥🔥",
    category: "Prefix Sum",
  },

  {
    id: "hm-1",
    name: "Longest Consecutive Sequence",
    url: "https://leetcode.com/problems/longest-consecutive-sequence",
    difficulty: "Medium",
    pattern: "Hash Set",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Hash Map / Set",
  },
  {
    id: "hm-2",
    name: "Word Pattern",
    url: "https://leetcode.com/problems/word-pattern",
    difficulty: "Easy",
    pattern: "Hash Map",
    companies: ["Google"],
    frequency: "🔥",
    category: "Hash Map / Set",
  },
  {
    id: "hm-3",
    name: "Isomorphic Strings",
    url: "https://leetcode.com/problems/isomorphic-strings",
    difficulty: "Easy",
    pattern: "Hash Map",
    companies: ["LinkedIn"],
    frequency: "🔥",
    category: "Hash Map / Set",
  },
  {
    id: "hm-4",
    name: "Top K Frequent Elements",
    url: "https://leetcode.com/problems/top-k-frequent-elements",
    difficulty: "Medium",
    pattern: "Hash + Heap",
    companies: ["Google", "Amazon", "Meta", "Apple", "Netflix"],
    frequency: "🔥🔥🔥",
    category: "Hash Map / Set",
  },
  {
    id: "hm-5",
    name: "Contains Duplicate II",
    url: "https://leetcode.com/problems/contains-duplicate-ii",
    difficulty: "Easy",
    pattern: "Hash Map",
    companies: ["Amazon"],
    frequency: "🔥",
    category: "Hash Map / Set",
  },

  {
    id: "st-1",
    name: "Valid Parentheses",
    url: "https://leetcode.com/problems/valid-parentheses",
    difficulty: "Easy",
    pattern: "Stack",
    companies: ["Apple", "Amazon", "Google"],
    frequency: "🔥🔥🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-2",
    name: "Daily Temperatures",
    url: "https://leetcode.com/problems/daily-temperatures",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    companies: ["Netflix", "Google"],
    frequency: "🔥🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-3",
    name: "Next Greater Element I",
    url: "https://leetcode.com/problems/next-greater-element-i",
    difficulty: "Easy",
    pattern: "Monotonic Stack",
    companies: ["Google"],
    frequency: "🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-4",
    name: "Next Greater Element II",
    url: "https://leetcode.com/problems/next-greater-element-ii",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    companies: ["Amazon"],
    frequency: "🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-5",
    name: "Largest Rectangle in Histogram",
    url: "https://leetcode.com/problems/largest-rectangle-in-histogram",
    difficulty: "Hard",
    pattern: "Monotonic Stack",
    companies: ["Microsoft", "Google"],
    frequency: "🔥🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-6",
    name: "Evaluate Reverse Polish Notation",
    url: "https://leetcode.com/problems/evaluate-reverse-polish-notation",
    difficulty: "Medium",
    pattern: "Stack",
    companies: ["Google"],
    frequency: "🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-7",
    name: "Basic Calculator II",
    url: "https://leetcode.com/problems/basic-calculator-ii",
    difficulty: "Medium",
    pattern: "Stack",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-8",
    name: "Basic Calculator III",
    url: "https://leetcode.com/problems/basic-calculator-iii",
    difficulty: "Hard",
    pattern: "Stack",
    companies: ["Google"],
    frequency: "🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-9",
    name: "Simplify Path",
    url: "https://leetcode.com/problems/simplify-path",
    difficulty: "Medium",
    pattern: "Stack",
    companies: ["Google"],
    frequency: "🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-10",
    name: "Asteroid Collision",
    url: "https://leetcode.com/problems/asteroid-collision",
    difficulty: "Medium",
    pattern: "Stack",
    companies: ["Microsoft", "Databricks"],
    frequency: "🔥🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-11",
    name: "Decode String",
    url: "https://leetcode.com/problems/decode-string",
    difficulty: "Medium",
    pattern: "Stack",
    companies: ["Amazon", "Databricks"],
    frequency: "🔥🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "st-12",
    name: "Sum of Subarray Minimums",
    url: "https://leetcode.com/problems/sum-of-subarray-minimums",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    companies: ["Amazon"],
    frequency: "🔥",
    category: "Stack / Monotonic Stack",
  },

  {
    id: "ll-1",
    name: "Reverse Linked List",
    url: "https://leetcode.com/problems/reverse-linked-list",
    difficulty: "Easy",
    pattern: "Iteration/Recursion",
    companies: ["Apple", "Amazon", "Google"],
    frequency: "🔥🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-2",
    name: "Merge Two Sorted Lists",
    url: "https://leetcode.com/problems/merge-two-sorted-lists",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Amazon", "Meta", "Microsoft"],
    frequency: "🔥🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-3",
    name: "Linked List Cycle",
    url: "https://leetcode.com/problems/linked-list-cycle",
    difficulty: "Easy",
    pattern: "Fast/Slow Pointers",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-4",
    name: "Add Two Numbers",
    url: "https://leetcode.com/problems/add-two-numbers",
    difficulty: "Medium",
    pattern: "Math",
    companies: ["Microsoft", "Amazon"],
    frequency: "🔥🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-5",
    name: "Copy List with Random Pointer",
    url: "https://leetcode.com/problems/copy-list-with-random-pointer",
    difficulty: "Medium",
    pattern: "Hash Map",
    companies: ["Meta", "Microsoft"],
    frequency: "🔥🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-6",
    name: "Reorder List",
    url: "https://leetcode.com/problems/reorder-list",
    difficulty: "Medium",
    pattern: "Fast/Slow + Reverse",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-7",
    name: "Insert into a Sorted Circular Linked List",
    url: "https://leetcode.com/problems/insert-into-a-sorted-circular-linked-list",
    difficulty: "Medium",
    pattern: "Linked List",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-8",
    name: "Reverse Linked List II",
    url: "https://leetcode.com/problems/reverse-linked-list-ii",
    difficulty: "Medium",
    pattern: "In-place Reversal",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-9",
    name: "Swap Nodes in Pairs",
    url: "https://leetcode.com/problems/swap-nodes-in-pairs",
    difficulty: "Medium",
    pattern: "Recursion",
    companies: ["Google"],
    frequency: "🔥",
    category: "Linked List",
  },
  {
    id: "ll-10",
    name: "Reverse Nodes in k-Group",
    url: "https://leetcode.com/problems/reverse-nodes-in-k-group",
    difficulty: "Hard",
    pattern: "In-place Reversal",
    companies: ["Microsoft"],
    frequency: "🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-11",
    name: "Merge k Sorted Lists",
    url: "https://leetcode.com/problems/merge-k-sorted-lists",
    difficulty: "Hard",
    pattern: "Heap/Divide&Conquer",
    companies: [
      "Amazon",
      "Google",
      "Meta",
      "Palantir",
      "Anthropic",
      "Microsoft",
      "Intuit",
    ],
    frequency: "🔥🔥🔥",
    category: "Linked List",
  },
  {
    id: "ll-12",
    name: "Odd Even Linked List",
    url: "https://leetcode.com/problems/odd-even-linked-list",
    difficulty: "Medium",
    pattern: "Linked List",
    companies: ["Google"],
    frequency: "🔥",
    category: "Linked List",
  },
  {
    id: "ll-13",
    name: "Find the Duplicate Number",
    url: "https://leetcode.com/problems/find-the-duplicate-number",
    difficulty: "Medium",
    pattern: "Floyd's Cycle",
    companies: ["Google", "Tesla"],
    frequency: "🔥🔥",
    category: "Linked List",
  },

  {
    id: "bs-1",
    name: "Binary Search",
    url: "https://leetcode.com/problems/binary-search",
    difficulty: "Easy",
    pattern: "Binary Search",
    companies: ["Google"],
    frequency: "🔥",
    category: "Binary Search",
  },
  {
    id: "bs-2",
    name: "Search in Rotated Sorted Array",
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array",
    difficulty: "Medium",
    pattern: "Modified Binary Search",
    companies: ["Google", "Amazon", "Tesla"],
    frequency: "🔥🔥🔥",
    category: "Binary Search",
  },
  {
    id: "bs-3",
    name: "Find Minimum in Rotated Sorted Array",
    url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array",
    difficulty: "Medium",
    pattern: "Binary Search",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Binary Search",
  },
  {
    id: "bs-4",
    name: "Find Peak Element",
    url: "https://leetcode.com/problems/find-peak-element",
    difficulty: "Medium",
    pattern: "Binary Search",
    companies: ["Meta", "Google"],
    frequency: "🔥🔥",
    category: "Binary Search",
  },
  {
    id: "bs-5",
    name: "Search a 2D Matrix",
    url: "https://leetcode.com/problems/search-a-2d-matrix",
    difficulty: "Medium",
    pattern: "Binary Search",
    companies: ["Apple", "Microsoft"],
    frequency: "🔥🔥",
    category: "Binary Search",
  },
  {
    id: "bs-6",
    name: "Search a 2D Matrix II",
    url: "https://leetcode.com/problems/search-a-2d-matrix-ii",
    difficulty: "Medium",
    pattern: "Binary Search",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Binary Search",
  },
  {
    id: "bs-7",
    name: "Koko Eating Bananas",
    url: "https://leetcode.com/problems/koko-eating-bananas",
    difficulty: "Medium",
    pattern: "Binary Search on Answer",
    companies: ["Amazon", "Google", "Netflix"],
    frequency: "🔥🔥🔥",
    category: "Binary Search",
  },
  {
    id: "bs-8",
    name: "Capacity To Ship Packages Within D Days",
    url: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days",
    difficulty: "Medium",
    pattern: "Binary Search on Answer",
    companies: ["Databricks"],
    frequency: "🔥🔥",
    category: "Binary Search",
  },
  {
    id: "bs-9",
    name: "Median of Two Sorted Arrays",
    url: "https://leetcode.com/problems/median-of-two-sorted-arrays",
    difficulty: "Hard",
    pattern: "Binary Search",
    companies: ["Google", "Amazon", "Apple", "Microsoft"],
    frequency: "🔥🔥🔥",
    category: "Binary Search",
  },
  {
    id: "bs-10",
    name: "Search Insert Position",
    url: "https://leetcode.com/problems/search-insert-position",
    difficulty: "Easy",
    pattern: "Binary Search",
    companies: ["Google"],
    frequency: "🔥",
    category: "Binary Search",
  },

  {
    id: "tr-1",
    name: "Maximum Depth of Binary Tree",
    url: "https://leetcode.com/problems/maximum-depth-of-binary-tree",
    difficulty: "Easy",
    pattern: "DFS/BFS",
    companies: ["Amazon", "Google"],
    frequency: "🔥🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-2",
    name: "Same Tree",
    url: "https://leetcode.com/problems/same-tree",
    difficulty: "Easy",
    pattern: "DFS",
    companies: ["Google"],
    frequency: "🔥",
    category: "Trees",
  },
  {
    id: "tr-3",
    name: "Symmetric Tree",
    url: "https://leetcode.com/problems/symmetric-tree",
    difficulty: "Easy",
    pattern: "DFS/BFS",
    companies: ["Microsoft"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-4",
    name: "Balanced Binary Tree",
    url: "https://leetcode.com/problems/balanced-binary-tree",
    difficulty: "Easy",
    pattern: "DFS",
    companies: ["Adobe", "Walmart"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-5",
    name: "Invert Binary Tree",
    url: "https://leetcode.com/problems/invert-binary-tree",
    difficulty: "Easy",
    pattern: "DFS",
    companies: ["Amazon"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-6",
    name: "Binary Tree Level Order Traversal",
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal",
    difficulty: "Medium",
    pattern: "BFS",
    companies: ["Google", "Amazon", "Microsoft", "Uber", "Intuit"],
    frequency: "🔥🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-7",
    name: "Binary Tree Zigzag Level Order Traversal",
    url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal",
    difficulty: "Medium",
    pattern: "BFS",
    companies: ["Amazon"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-8",
    name: "Binary Tree Right Side View",
    url: "https://leetcode.com/problems/binary-tree-right-side-view",
    difficulty: "Medium",
    pattern: "BFS/DFS",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-9",
    name: "Validate Binary Search Tree",
    url: "https://leetcode.com/problems/validate-binary-search-tree",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-10",
    name: "Lowest Common Ancestor of a Binary Tree",
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Meta", "Amazon", "Apple", "Google"],
    frequency: "🔥🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-11",
    name: "Lowest Common Ancestor of a BST",
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree",
    difficulty: "Medium",
    pattern: "BST",
    companies: ["LinkedIn", "Google"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-12",
    name: "Kth Smallest Element in a BST",
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst",
    difficulty: "Medium",
    pattern: "Inorder",
    companies: ["Google", "Amazon", "Walmart"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-13",
    name: "Construct Binary Tree from Preorder and Inorder Traversal",
    url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal",
    difficulty: "Medium",
    pattern: "Divide & Conquer",
    companies: ["Microsoft", "Google"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-14",
    name: "Serialize and Deserialize Binary Tree",
    url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree",
    difficulty: "Hard",
    pattern: "BFS/DFS",
    companies: ["Google", "Amazon", "Apple", "Meta", "Netflix", "Anthropic"],
    frequency: "🔥🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-15",
    name: "Binary Tree Maximum Path Sum",
    url: "https://leetcode.com/problems/binary-tree-maximum-path-sum",
    difficulty: "Hard",
    pattern: "DFS",
    companies: ["Google", "Amazon", "Microsoft"],
    frequency: "🔥🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-16",
    name: "Diameter of Binary Tree",
    url: "https://leetcode.com/problems/diameter-of-binary-tree",
    difficulty: "Easy",
    pattern: "DFS",
    companies: ["Meta", "Amazon", "Google"],
    frequency: "🔥🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-17",
    name: "Path Sum III",
    url: "https://leetcode.com/problems/path-sum-iii",
    difficulty: "Medium",
    pattern: "DFS + Prefix Sum",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-18",
    name: "Count Good Nodes in Binary Tree",
    url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Google"],
    frequency: "🔥",
    category: "Trees",
  },
  {
    id: "tr-19",
    name: "Sum Root to Leaf Numbers",
    url: "https://leetcode.com/problems/sum-root-to-leaf-numbers",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Apple", "Google", "Flipkart", "Microsoft"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-20",
    name: "Check Completeness of a Binary Tree",
    url: "https://leetcode.com/problems/check-completeness-of-a-binary-tree",
    difficulty: "Medium",
    pattern: "BFS",
    companies: ["Apple"],
    frequency: "🔥",
    category: "Trees",
  },
  {
    id: "tr-21",
    name: "Binary Tree Vertical Order Traversal",
    url: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree",
    difficulty: "Medium",
    pattern: "BFS",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-22",
    name: "All Nodes Distance K in Binary Tree",
    url: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree",
    difficulty: "Medium",
    pattern: "BFS + Graph",
    companies: ["Databricks", "Google"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-23",
    name: "Range Sum of BST",
    url: "https://leetcode.com/problems/range-sum-of-bst",
    difficulty: "Easy",
    pattern: "BST",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-24",
    name: "Find Leaves of Binary Tree",
    url: "https://leetcode.com/problems/find-leaves-of-binary-tree",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Google", "LinkedIn"],
    frequency: "🔥🔥",
    category: "Trees",
  },
  {
    id: "tr-25",
    name: "Maximum Difference Between Node and Ancestor",
    url: "https://leetcode.com/problems/maximum-difference-between-node-and-ancestor",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Amazon", "Google"],
    frequency: "🔥",
    category: "Trees",
  },

  {
    id: "gr-1",
    name: "Number of Islands",
    url: "https://leetcode.com/problems/number-of-islands",
    difficulty: "Medium",
    pattern: "DFS/BFS",
    companies: [
      "Google",
      "Amazon",
      "Meta",
      "Apple",
      "Microsoft",
      "Palantir",
      "Anthropic",
      "Adobe",
    ],
    frequency: "🔥🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-2",
    name: "Clone Graph",
    url: "https://leetcode.com/problems/clone-graph",
    difficulty: "Medium",
    pattern: "DFS/BFS",
    companies: ["Meta", "Microsoft", "Amazon", "Google", "Uber", "Apple"],
    frequency: "🔥🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-3",
    name: "Course Schedule",
    url: "https://leetcode.com/problems/course-schedule",
    difficulty: "Medium",
    pattern: "Topological Sort",
    companies: ["Amazon", "Apple", "Palantir"],
    frequency: "🔥🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-4",
    name: "Course Schedule II",
    url: "https://leetcode.com/problems/course-schedule-ii",
    difficulty: "Medium",
    pattern: "Topological Sort",
    companies: ["Google", "Netflix", "Palantir", "Anthropic"],
    frequency: "🔥🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-5",
    name: "Rotting Oranges",
    url: "https://leetcode.com/problems/rotting-oranges",
    difficulty: "Medium",
    pattern: "BFS",
    companies: ["Amazon", "Databricks"],
    frequency: "🔥🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-6",
    name: "Word Ladder",
    url: "https://leetcode.com/problems/word-ladder",
    difficulty: "Hard",
    pattern: "BFS",
    companies: ["Google", "Amazon", "LinkedIn"],
    frequency: "🔥🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-7",
    name: "Accounts Merge",
    url: "https://leetcode.com/problems/accounts-merge",
    difficulty: "Medium",
    pattern: "Union-Find/DFS",
    companies: ["Meta", "Google"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-8",
    name: "Making a Large Island",
    url: "https://leetcode.com/problems/making-a-large-island",
    difficulty: "Hard",
    pattern: "DFS + Union-Find",
    companies: ["Meta", "Amazon"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-9",
    name: "Shortest Path in Binary Matrix",
    url: "https://leetcode.com/problems/shortest-path-in-binary-matrix",
    difficulty: "Medium",
    pattern: "BFS",
    companies: ["Meta", "Microsoft"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-10",
    name: "Network Delay Time",
    url: "https://leetcode.com/problems/network-delay-time",
    difficulty: "Medium",
    pattern: "Dijkstra",
    companies: ["Netflix", "Google", "Uber"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-11",
    name: "Cheapest Flights Within K Stops",
    url: "https://leetcode.com/problems/cheapest-flights-within-k-stops",
    difficulty: "Medium",
    pattern: "BFS/Bellman-Ford",
    companies: ["Microsoft", "Databricks"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-12",
    name: "Evaluate Division",
    url: "https://leetcode.com/problems/evaluate-division",
    difficulty: "Medium",
    pattern: "DFS/Union-Find",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-13",
    name: "Alien Dictionary",
    url: "https://leetcode.com/problems/alien-dictionary",
    difficulty: "Hard",
    pattern: "Topological Sort",
    companies: ["Google", "OpenAI", "Tesla"],
    frequency: "🔥🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-14",
    name: "Walls and Gates",
    url: "https://leetcode.com/problems/walls-and-gates",
    difficulty: "Medium",
    pattern: "BFS",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-15",
    name: "Number of Provinces",
    url: "https://leetcode.com/problems/number-of-provinces",
    difficulty: "Medium",
    pattern: "Union-Find/DFS",
    companies: ["Amazon"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-16",
    name: "Max Area of Island",
    url: "https://leetcode.com/problems/max-area-of-island",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Palantir"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-17",
    name: "Flood Fill",
    url: "https://leetcode.com/problems/flood-fill",
    difficulty: "Easy",
    pattern: "DFS/BFS",
    companies: ["Google", "Adobe", "Apple"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-18",
    name: "Surrounded-md Regions",
    url: "https://leetcode.com/problems/surrounded-regions",
    difficulty: "Medium",
    pattern: "DFS/BFS",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-19",
    name: "Pacific Atlantic Water Flow",
    url: "https://leetcode.com/problems/pacific-atlantic-water-flow",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Google"],
    frequency: "🔥",
    category: "Graphs",
  },
  {
    id: "gr-20",
    name: "Shortest Path in a Grid with Obstacles Elimination",
    url: "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination",
    difficulty: "Hard",
    pattern: "BFS",
    companies: ["Google"],
    frequency: "🔥",
    category: "Graphs",
  },
  {
    id: "gr-21",
    name: "All Ancestors of a Node in DAG",
    url: "https://leetcode.com/problems/all-ancestors-of-a-node-in-a-directed-acyclic-graph",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Palantir"],
    frequency: "🔥",
    category: "Graphs",
  },
  {
    id: "gr-22",
    name: "Is Graph Bipartite?",
    url: "https://leetcode.com/problems/is-graph-bipartite",
    difficulty: "Medium",
    pattern: "BFS/DFS",
    companies: ["Google"],
    frequency: "🔥",
    category: "Graphs",
  },
  {
    id: "gr-23",
    name: "Number of Closed Islands",
    url: "https://leetcode.com/problems/number-of-closed-islands",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Google"],
    frequency: "🔥",
    category: "Graphs",
  },
  {
    id: "gr-24",
    name: "Longest Increasing Path in a Matrix",
    url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix",
    difficulty: "Hard",
    pattern: "DFS + Memo",
    companies: ["Meta", "Google", "Microsoft", "Uber", "Adobe"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "gr-25",
    name: "Bus Routes",
    url: "https://leetcode.com/problems/bus-routes",
    difficulty: "Hard",
    pattern: "BFS",
    companies: ["Apple"],
    frequency: "🔥",
    category: "Graphs",
  },

  {
    id: "hp-1",
    name: "Kth Largest Element in an Array",
    url: "https://leetcode.com/problems/kth-largest-element-in-an-array",
    difficulty: "Medium",
    pattern: "Heap/Quickselect",
    companies: ["Google", "Amazon", "Meta"],
    frequency: "🔥🔥🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "hp-2",
    name: "K Closest Points to Origin",
    url: "https://leetcode.com/problems/k-closest-points-to-origin",
    difficulty: "Medium",
    pattern: "Heap",
    companies: ["Amazon", "Google", "Databricks"],
    frequency: "🔥🔥🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "hp-3",
    name: "Find Median from Data Stream",
    url: "https://leetcode.com/problems/find-median-from-data-stream",
    difficulty: "Hard",
    pattern: "Two Heaps",
    companies: ["Amazon", "Netflix", "Google", "Apple"],
    frequency: "🔥🔥🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "hp-4",
    name: "Task Scheduler",
    url: "https://leetcode.com/problems/task-scheduler",
    difficulty: "Medium",
    pattern: "Heap + Greedy",
    companies: ["Amazon", "Google"],
    frequency: "🔥🔥🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "hp-5",
    name: "Reorganize String",
    url: "https://leetcode.com/problems/reorganize-string",
    difficulty: "Medium",
    pattern: "Heap",
    companies: ["Amazon", "Tesla"],
    frequency: "🔥🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "hp-6",
    name: "Meeting Rooms II",
    url: "https://leetcode.com/problems/meeting-rooms-ii",
    difficulty: "Medium",
    pattern: "Heap",
    companies: ["Google", "Netflix", "OpenAI"],
    frequency: "🔥🔥🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "hp-7",
    name: "Smallest Range Covering Elements from K Lists",
    url: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists",
    difficulty: "Hard",
    pattern: "Heap",
    companies: ["Google"],
    frequency: "🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "hp-8",
    name: "Sort Characters By Frequency",
    url: "https://leetcode.com/problems/sort-characters-by-frequency",
    difficulty: "Medium",
    pattern: "Heap/Bucket Sort",
    companies: ["Google"],
    frequency: "🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "hp-9",
    name: "Find K Pairs with Smallest Sums",
    url: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums",
    difficulty: "Medium",
    pattern: "Heap",
    companies: ["Google"],
    frequency: "🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "hp-10",
    name: "K-th Smallest Prime Fraction",
    url: "https://leetcode.com/problems/k-th-smallest-prime-fraction",
    difficulty: "Medium",
    pattern: "Binary Search/Heap",
    companies: ["Google"],
    frequency: "🔥",
    category: "Heap / Priority Queue",
  },

  {
    id: "dp-1",
    name: "Climbing Stairs",
    url: "https://leetcode.com/problems/climbing-stairs",
    difficulty: "Easy",
    pattern: "1D DP",
    companies: ["Amazon"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-2",
    name: "House Robber",
    url: "https://leetcode.com/problems/house-robber",
    difficulty: "Medium",
    pattern: "1D DP",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-3",
    name: "House Robber II",
    url: "https://leetcode.com/problems/house-robber-ii",
    difficulty: "Medium",
    pattern: "1D DP",
    companies: ["LinkedIn"],
    frequency: "🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-4",
    name: "Coin Change",
    url: "https://leetcode.com/problems/coin-change",
    difficulty: "Medium",
    pattern: "Unbounded Knapsack",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-5",
    name: "Coin Change II",
    url: "https://leetcode.com/problems/coin-change-ii",
    difficulty: "Medium",
    pattern: "Unbounded Knapsack",
    companies: ["Amazon"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-6",
    name: "Word Break",
    url: "https://leetcode.com/problems/word-break",
    difficulty: "Medium",
    pattern: "DP + Trie",
    companies: ["Meta", "Amazon", "Apple", "Databricks", "Anthropic"],
    frequency: "🔥🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-7",
    name: "Word Break II",
    url: "https://leetcode.com/problems/word-break-ii",
    difficulty: "Hard",
    pattern: "DP + Backtracking",
    companies: ["Amazon"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-8",
    name: "Longest Palindromic Substring",
    url: "https://leetcode.com/problems/longest-palindromic-substring",
    difficulty: "Medium",
    pattern: "Expand Around Center",
    companies: ["Amazon", "Google", "Meta"],
    frequency: "🔥🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-9",
    name: "Decode Ways",
    url: "https://leetcode.com/problems/decode-ways",
    difficulty: "Medium",
    pattern: "1D DP",
    companies: ["Meta", "LinkedIn"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-10",
    name: "Unique Paths",
    url: "https://leetcode.com/problems/unique-paths",
    difficulty: "Medium",
    pattern: "2D DP",
    companies: ["Google", "Uber", "Amazon", "Adobe"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-11",
    name: "Longest Increasing Subsequence",
    url: "https://leetcode.com/problems/longest-increasing-subsequence",
    difficulty: "Medium",
    pattern: "DP + Binary Search",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-12",
    name: "Maximum Product Subarray",
    url: "https://leetcode.com/problems/maximum-product-subarray",
    difficulty: "Medium",
    pattern: "DP",
    companies: ["Amazon", "LinkedIn", "Microsoft"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-13",
    name: "Jump Game",
    url: "https://leetcode.com/problems/jump-game",
    difficulty: "Medium",
    pattern: "Greedy/DP",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-14",
    name: "Jump Game II",
    url: "https://leetcode.com/problems/jump-game-ii",
    difficulty: "Medium",
    pattern: "Greedy",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-15",
    name: "Best Time to Buy and Sell Stock",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock",
    difficulty: "Easy",
    pattern: "DP/Greedy",
    companies: ["Meta", "Amazon", "Apple", "Microsoft"],
    frequency: "🔥🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-16",
    name: "Edit Distance",
    url: "https://leetcode.com/problems/edit-distance",
    difficulty: "Hard",
    pattern: "2D DP",
    companies: ["Google", "Netflix", "LinkedIn", "Uber", "Adobe"],
    frequency: "🔥🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-17",
    name: "Longest Common Subsequence",
    url: "https://leetcode.com/problems/longest-common-subsequence",
    difficulty: "Medium",
    pattern: "2D DP",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-18",
    name: "Partition Equal Subset Sum",
    url: "https://leetcode.com/problems/partition-equal-subset-sum",
    difficulty: "Medium",
    pattern: "0/1 Knapsack",
    companies: ["Google", "Amazon", "Uber", "Flipkart"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-19",
    name: "Burst Balloons",
    url: "https://leetcode.com/problems/burst-balloons",
    difficulty: "Hard",
    pattern: "Interval DP",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-20",
    name: "Regular Expression Matching",
    url: "https://leetcode.com/problems/regular-expression-matching",
    difficulty: "Hard",
    pattern: "2D DP",
    companies: ["Microsoft", "Palantir"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-21",
    name: "Maximum Profit in Job Scheduling",
    url: "https://leetcode.com/problems/maximum-profit-in-job-scheduling",
    difficulty: "Hard",
    pattern: "DP + Binary Search",
    companies: ["Apple"],
    frequency: "🔥🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-22",
    name: "N-th Tribonacci Number",
    url: "https://leetcode.com/problems/n-th-tribonacci-number",
    difficulty: "Easy",
    pattern: "1D DP",
    companies: ["Google"],
    frequency: "🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-23",
    name: "Number of Dice Rolls With Target Sum",
    url: "https://leetcode.com/problems/number-of-dice-rolls-with-target-sum",
    difficulty: "Medium",
    pattern: "DP",
    companies: ["Google"],
    frequency: "🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-24",
    name: "Frog Jump",
    url: "https://leetcode.com/problems/frog-jump",
    difficulty: "Hard",
    pattern: "DP",
    companies: ["Google"],
    frequency: "🔥",
    category: "Dynamic Programming",
  },
  {
    id: "dp-25",
    name: "Split Array Largest Sum",
    url: "https://leetcode.com/problems/split-array-largest-sum",
    difficulty: "Hard",
    pattern: "Binary Search + DP",
    companies: ["Google"],
    frequency: "🔥",
    category: "Dynamic Programming",
  },

  {
    id: "bt-1",
    name: "Subsets",
    url: "https://leetcode.com/problems/subsets",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Meta", "Amazon"],
    frequency: "🔥🔥🔥",
    category: "Backtracking",
  },
  {
    id: "bt-2",
    name: "Permutations",
    url: "https://leetcode.com/problems/permutations",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Meta", "Google"],
    frequency: "🔥🔥🔥",
    category: "Backtracking",
  },
  {
    id: "bt-3",
    name: "Permutations II",
    url: "https://leetcode.com/problems/permutations-ii",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Google"],
    frequency: "🔥",
    category: "Backtracking",
  },
  {
    id: "bt-4",
    name: "Combination Sum",
    url: "https://leetcode.com/problems/combination-sum",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Google", "Microsoft", "Amazon"],
    frequency: "🔥🔥🔥",
    category: "Backtracking",
  },
  {
    id: "bt-5",
    name: "Letter Combinations of a Phone Number",
    url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Meta", "Google"],
    frequency: "🔥🔥🔥",
    category: "Backtracking",
  },
  {
    id: "bt-6",
    name: "Word Search",
    url: "https://leetcode.com/problems/word-search",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Backtracking",
  },
  {
    id: "bt-7",
    name: "Word Search II",
    url: "https://leetcode.com/problems/word-search-ii",
    difficulty: "Hard",
    pattern: "Backtracking + Trie",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Backtracking",
  },
  {
    id: "bt-8",
    name: "N-Queens",
    url: "https://leetcode.com/problems/n-queens",
    difficulty: "Hard",
    pattern: "Backtracking",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Backtracking",
  },
  {
    id: "bt-9",
    name: "Palindrome Partitioning",
    url: "https://leetcode.com/problems/palindrome-partitioning",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Google"],
    frequency: "🔥",
    category: "Backtracking",
  },
  {
    id: "bt-10",
    name: "Generate Parentheses",
    url: "https://leetcode.com/problems/generate-parentheses",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Backtracking",
  },
  {
    id: "bt-11",
    name: "Remove Invalid Parentheses",
    url: "https://leetcode.com/problems/remove-invalid-parentheses",
    difficulty: "Hard",
    pattern: "BFS/Backtracking",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Backtracking",
  },
  {
    id: "bt-12",
    name: "Expression Add Operators",
    url: "https://leetcode.com/problems/expression-add-operators",
    difficulty: "Hard",
    pattern: "Backtracking",
    companies: ["Meta"],
    frequency: "🔥",
    category: "Backtracking",
  },
  {
    id: "bt-13",
    name: "Sudoku Solver",
    url: "https://leetcode.com/problems/sudoku-solver",
    difficulty: "Hard",
    pattern: "Backtracking",
    companies: ["Microsoft"],
    frequency: "🔥",
    category: "Backtracking",
  },

  {
    id: "iv-1",
    name: "Merge Intervals",
    url: "https://leetcode.com/problems/merge-intervals",
    difficulty: "Medium",
    pattern: "Sorting",
    companies: [
      "Google",
      "Amazon",
      "Meta",
      "Apple",
      "Netflix",
      "Palantir",
      "LinkedIn",
    ],
    frequency: "🔥🔥🔥",
    category: "Intervals",
  },
  {
    id: "iv-2",
    name: "Insert Interval",
    url: "https://leetcode.com/problems/insert-interval",
    difficulty: "Medium",
    pattern: "Intervals",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Intervals",
  },
  {
    id: "iv-3",
    name: "Non-overlapping Intervals",
    url: "https://leetcode.com/problems/non-overlapping-intervals",
    difficulty: "Medium",
    pattern: "Greedy",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Intervals",
  },
  {
    id: "iv-4",
    name: "Meeting Rooms",
    url: "https://leetcode.com/problems/meeting-rooms",
    difficulty: "Easy",
    pattern: "Sorting",
    companies: ["Google"],
    frequency: "🔥",
    category: "Intervals",
  },
  {
    id: "iv-5",
    name: "Meeting Rooms III",
    url: "https://leetcode.com/problems/meeting-rooms-iii",
    difficulty: "Hard",
    pattern: "Heap",
    companies: ["Google"],
    frequency: "🔥",
    category: "Intervals",
  },
  {
    id: "iv-6",
    name: "Minimum Number of Arrows to Burst Balloons",
    url: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons",
    difficulty: "Medium",
    pattern: "Greedy",
    companies: ["Google"],
    frequency: "🔥",
    category: "Intervals",
  },
  {
    id: "iv-7",
    name: "Employee Free Time",
    url: "https://leetcode.com/problems/employee-free-time",
    difficulty: "Hard",
    pattern: "Heap",
    companies: ["Google"],
    frequency: "🔥",
    category: "Intervals",
  },

  {
    id: "ti-1",
    name: "Implement Trie (Prefix Tree)",
    url: "https://leetcode.com/problems/implement-trie-prefix-tree",
    difficulty: "Medium",
    pattern: "Trie",
    companies: [
      "Google",
      "Netflix",
      "OpenAI",
      "Tesla",
      "Anthropic",
      "Uber",
      "Salesforce",
      "Amazon",
    ],
    frequency: "🔥🔥🔥",
    category: "Trie",
  },
  {
    id: "ti-2",
    name: "Design Add and Search Words Data Structure",
    url: "https://leetcode.com/problems/design-add-and-search-words-data-structure",
    difficulty: "Medium",
    pattern: "Trie + DFS",
    companies: ["LinkedIn", "Google"],
    frequency: "🔥🔥",
    category: "Trie",
  },
  {
    id: "ti-3",
    name: "Search Suggestions System",
    url: "https://leetcode.com/problems/search-suggestions-system",
    difficulty: "Medium",
    pattern: "Trie",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Trie",
  },

  {
    id: "de-1",
    name: "LRU Cache",
    url: "https://leetcode.com/problems/lru-cache",
    difficulty: "Medium",
    pattern: "Hash + DLL",
    companies: [
      "Google",
      "Amazon",
      "Meta",
      "Apple",
      "Microsoft",
      "Netflix",
      "OpenAI",
      "Palantir",
      "Tesla",
      "Databricks",
      "LinkedIn",
      "Anthropic",
    ],
    frequency: "🔥🔥🔥",
    category: "Design",
  },
  {
    id: "de-2",
    name: "LFU Cache",
    url: "https://leetcode.com/problems/lfu-cache",
    difficulty: "Hard",
    pattern: "Hash + DLL",
    companies: ["Amazon", "OpenAI", "Google"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-3",
    name: "Insert Delete GetRandom O(1)",
    url: "https://leetcode.com/problems/insert-delete-getrandom-o1",
    difficulty: "Medium",
    pattern: "Hash + Array",
    companies: ["Amazon", "LinkedIn"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-4",
    name: "Design Hit Counter",
    url: "https://leetcode.com/problems/design-hit-counter",
    difficulty: "Medium",
    pattern: "Queue/Array",
    companies: ["Netflix", "Databricks", "Anthropic"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-5",
    name: "Design Tic-Tac-Toe",
    url: "https://leetcode.com/problems/design-tic-tac-toe",
    difficulty: "Medium",
    pattern: "Design",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-6",
    name: "Time Based Key-Value Store",
    url: "https://leetcode.com/problems/time-based-key-value-store",
    difficulty: "Medium",
    pattern: "Hash + Binary Search",
    companies: ["OpenAI", "Databricks", "Anthropic"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-7",
    name: "Snapshot Array",
    url: "https://leetcode.com/problems/snapshot-array",
    difficulty: "Medium",
    pattern: "Hash + Binary Search",
    companies: ["OpenAI", "Databricks"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-8",
    name: "Dot Product of Two Sparse Vectors",
    url: "https://leetcode.com/problems/dot-product-of-two-sparse-vectors",
    difficulty: "Medium",
    pattern: "Hash Map",
    companies: ["Meta"],
    frequency: "🔥🔥🔥",
    category: "Design",
  },
  {
    id: "de-9",
    name: "Design In-Memory File System",
    url: "https://leetcode.com/problems/design-in-memory-file-system",
    difficulty: "Hard",
    pattern: "Trie/Tree",
    companies: ["Amazon", "Google"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-10",
    name: "Design Search Autocomplete System",
    url: "https://leetcode.com/problems/design-search-autocomplete-system",
    difficulty: "Hard",
    pattern: "Trie + Heap",
    companies: ["Amazon"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-11",
    name: "Max Stack",
    url: "https://leetcode.com/problems/max-stack",
    difficulty: "Hard",
    pattern: "Stack + Tree",
    companies: ["LinkedIn", "Databricks"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-12",
    name: "All O'one Data Structure",
    url: "https://leetcode.com/problems/all-oone-data-structure",
    difficulty: "Hard",
    pattern: "Hash + DLL",
    companies: ["LinkedIn", "Databricks"],
    frequency: "🔥",
    category: "Design",
  },
  {
    id: "de-13",
    name: "Nested List Weight Sum",
    url: "https://leetcode.com/problems/nested-list-weight-sum",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["Meta", "LinkedIn"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-14",
    name: "Nested List Weight Sum II",
    url: "https://leetcode.com/problems/nested-list-weight-sum-ii",
    difficulty: "Medium",
    pattern: "DFS",
    companies: ["LinkedIn"],
    frequency: "🔥",
    category: "Design",
  },
  {
    id: "de-15",
    name: "Design HashMap",
    url: "https://leetcode.com/problems/design-hashmap",
    difficulty: "Easy",
    pattern: "Design",
    companies: ["Tesla"],
    frequency: "🔥",
    category: "Design",
  },
  {
    id: "de-16",
    name: "Design Underground System",
    url: "https://leetcode.com/problems/design-underground-system",
    difficulty: "Medium",
    pattern: "Design",
    companies: ["Tesla"],
    frequency: "🔥",
    category: "Design",
  },
  {
    id: "de-17",
    name: "Web Crawler Multithreaded",
    url: "https://leetcode.com/problems/web-crawler-multithreaded",
    difficulty: "Medium",
    pattern: "BFS + Threads",
    companies: ["OpenAI", "Anthropic"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "de-18",
    name: "Random Pick with Weight",
    url: "https://leetcode.com/problems/random-pick-with-weight",
    difficulty: "Medium",
    pattern: "Prefix Sum + Binary Search",
    companies: ["Meta"],
    frequency: "🔥🔥",
    category: "Design",
  },

  {
    id: "mx-1",
    name: "Valid Sudoku",
    url: "https://leetcode.com/problems/valid-sudoku",
    difficulty: "Medium",
    pattern: "Hash Set",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Matrix",
  },
  {
    id: "mx-2",
    name: "Spiral Matrix",
    url: "https://leetcode.com/problems/spiral-matrix",
    difficulty: "Medium",
    pattern: "Simulation",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Matrix",
  },
  {
    id: "mx-3",
    name: "Set Matrix Zeroes",
    url: "https://leetcode.com/problems/set-matrix-zeroes",
    difficulty: "Medium",
    pattern: "In-place",
    companies: ["Microsoft", "Google"],
    frequency: "🔥🔥",
    category: "Matrix",
  },
  {
    id: "mx-4",
    name: "01 Matrix",
    url: "https://leetcode.com/problems/01-matrix",
    difficulty: "Medium",
    pattern: "BFS",
    companies: ["Google", "Uber", "Intuit"],
    frequency: "🔥🔥",
    category: "Matrix",
  },
  {
    id: "mx-5",
    name: "Game of Life",
    url: "https://leetcode.com/problems/game-of-life",
    difficulty: "Medium",
    pattern: "Simulation",
    companies: ["OpenAI"],
    frequency: "🔥",
    category: "Matrix",
  },
  {
    id: "mx-6",
    name: "Toeplitz Matrix",
    url: "https://leetcode.com/problems/toeplitz-matrix",
    difficulty: "Easy",
    pattern: "Matrix",
    companies: ["Meta"],
    frequency: "🔥",
    category: "Matrix",
  },
  {
    id: "mx-7",
    name: "Diagonal Traverse",
    url: "https://leetcode.com/problems/diagonal-traverse",
    difficulty: "Medium",
    pattern: "Matrix",
    companies: ["Meta"],
    frequency: "🔥",
    category: "Matrix",
  },

  {
    id: "gy-1",
    name: "Candy",
    url: "https://leetcode.com/problems/candy",
    difficulty: "Hard",
    pattern: "Greedy",
    companies: ["Google"],
    frequency: "🔥",
    category: "Greedy",
  },
  {
    id: "gy-2",
    name: "Gas Station",
    url: "https://leetcode.com/problems/gas-station",
    difficulty: "Medium",
    pattern: "Greedy",
    companies: ["Google"],
    frequency: "🔥",
    category: "Greedy",
  },
  {
    id: "gy-3",
    name: "H-Index",
    url: "https://leetcode.com/problems/h-index",
    difficulty: "Medium",
    pattern: "Sorting/Counting",
    companies: ["Google"],
    frequency: "🔥",
    category: "Greedy",
  },

  {
    id: "mb-1",
    name: "Pow(x, n)",
    url: "https://leetcode.com/problems/powx-n",
    difficulty: "Medium",
    pattern: "Binary Exponentiation",
    companies: ["Meta", "Google"],
    frequency: "🔥🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "mb-2",
    name: "Happy Number",
    url: "https://leetcode.com/problems/happy-number",
    difficulty: "Easy",
    pattern: "Floyd's Cycle",
    companies: ["Google"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "mb-3",
    name: "Number of 1 Bits",
    url: "https://leetcode.com/problems/number-of-1-bits",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    companies: ["Tesla", "Google"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "mb-4",
    name: "Reverse Bits",
    url: "https://leetcode.com/problems/reverse-bits",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    companies: ["Tesla"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "mb-5",
    name: "Single Number",
    url: "https://leetcode.com/problems/single-number",
    difficulty: "Easy",
    pattern: "XOR",
    companies: ["Tesla"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "mb-6",
    name: "Counting Bits",
    url: "https://leetcode.com/problems/counting-bits",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    companies: ["Tesla"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "mb-7",
    name: "Sum of Two Integers",
    url: "https://leetcode.com/problems/sum-of-two-integers",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    companies: ["Tesla"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "mb-8",
    name: "Missing Number",
    url: "https://leetcode.com/problems/missing-number",
    difficulty: "Easy",
    pattern: "Math/XOR",
    companies: ["Microsoft"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },

  {
    id: "dc-1",
    name: "Majority Element",
    url: "https://leetcode.com/problems/majority-element",
    difficulty: "Easy",
    pattern: "Boyer-Moore",
    companies: ["Google"],
    frequency: "🔥",
    category: "Divide and Conquer",
  },
  {
    id: "dc-2",
    name: "Longest Substring with At Least K Repeating Characters",
    url: "https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters",
    difficulty: "Medium",
    pattern: "Divide & Conquer",
    companies: ["Google"],
    frequency: "🔥",
    category: "Divide and Conquer",
  },

  {
    id: "cc-1",
    name: "Print in Order",
    url: "https://leetcode.com/problems/print-in-order",
    difficulty: "Easy",
    pattern: "Concurrency",
    companies: ["Databricks"],
    frequency: "🔥",
    category: "Concurrency",
  },
  {
    id: "cc-2",
    name: "Print FooBar Alternately",
    url: "https://leetcode.com/problems/print-foobar-alternately",
    difficulty: "Medium",
    pattern: "Concurrency",
    companies: ["Databricks"],
    frequency: "🔥",
    category: "Concurrency",
  },
  {
    id: "cc-3",
    name: "Building H2O",
    url: "https://leetcode.com/problems/building-h2o",
    difficulty: "Medium",
    pattern: "Concurrency",
    companies: ["Databricks"],
    frequency: "🔥",
    category: "Concurrency",
  },
  {
    id: "cc-4",
    name: "The Dining Philosophers",
    url: "https://leetcode.com/problems/the-dining-philosophers",
    difficulty: "Medium",
    pattern: "Concurrency",
    companies: ["Databricks"],
    frequency: "🔥",
    category: "Concurrency",
  },
  {
    id: "cc-5",
    name: "Fizz Buzz Multithreaded",
    url: "https://leetcode.com/problems/fizz-buzz-multithreaded",
    difficulty: "Medium",
    pattern: "Concurrency",
    companies: ["Databricks"],
    frequency: "🔥",
    category: "Concurrency",
  },

  {
    id: "uf-1",
    name: "Number of Connected Components",
    url: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph",
    difficulty: "Medium",
    pattern: "Union Find",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Union-Find",
  },
  {
    id: "uf-2",
    name: "Graph Valid Tree",
    url: "https://leetcode.com/problems/graph-valid-tree",
    difficulty: "Medium",
    pattern: "Union Find",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Union-Find",
  },
  {
    id: "uf-3",
    name: "Redundant Connection",
    url: "https://leetcode.com/problems/redundant-connection",
    difficulty: "Medium",
    pattern: "Union-Find",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Union-Find",
  },
  {
    id: "uf-4",
    name: "Make Network Connected",
    url: "https://leetcode.com/problems/number-of-operations-to-make-network-connected",
    difficulty: "Medium",
    pattern: "Union-Find",
    companies: ["Meta", "Amazon"],
    frequency: "🔥",
    category: "Union-Find",
  },
  {
    id: "uf-5",
    name: "Regions Cut by Slashes",
    url: "https://leetcode.com/problems/regions-cut-by-slashes",
    difficulty: "Medium",
    pattern: "Union-Find",
    companies: ["Google"],
    frequency: "🔥",
    category: "Union-Find",
  },

  {
    id: "agp-1",
    name: "Open the Lock",
    url: "https://leetcode.com/problems/open-the-lock",
    difficulty: "Medium",
    pattern: "BFS",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "agp-2",
    name: "Path with Minimum Effort",
    url: "https://leetcode.com/problems/path-with-minimum-effort",
    difficulty: "Medium",
    pattern: "Dijkstra/Binary Search",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "agp-3",
    name: "Swim in Rising Water",
    url: "https://leetcode.com/problems/swim-in-rising-water",
    difficulty: "Hard",
    pattern: "Binary Search + BFS",
    companies: ["Google"],
    frequency: "🔥",
    category: "Graphs",
  },
  {
    id: "agp-4",
    name: "The Maze",
    url: "https://leetcode.com/problems/the-maze",
    difficulty: "Medium",
    pattern: "BFS/DFS",
    companies: ["Google", "Meta"],
    frequency: "🔥🔥",
    category: "Graphs",
  },
  {
    id: "agp-5",
    name: "The Maze II",
    url: "https://leetcode.com/problems/the-maze-ii",
    difficulty: "Medium",
    pattern: "Dijkstra",
    companies: ["Google"],
    frequency: "🔥",
    category: "Graphs",
  },
  {
    id: "agp-6",
    name: "The Maze III",
    url: "https://leetcode.com/problems/the-maze-iii",
    difficulty: "Hard",
    pattern: "Dijkstra",
    companies: ["Google"],
    frequency: "🔥",
    category: "Graphs",
  },
  {
    id: "agp-7",
    name: "Word Ladder II",
    url: "https://leetcode.com/problems/word-ladder-ii",
    difficulty: "Hard",
    pattern: "BFS + Backtracking",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Graphs",
  },

  {
    id: "abt-1",
    name: "Combinations",
    url: "https://leetcode.com/problems/combinations",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Meta", "Apple", "Google"],
    frequency: "🔥🔥",
    category: "Backtracking",
  },
  {
    id: "abt-2",
    name: "Combination Sum II",
    url: "https://leetcode.com/problems/combination-sum-ii",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Backtracking",
  },
  {
    id: "abt-3",
    name: "Subsets II",
    url: "https://leetcode.com/problems/subsets-ii",
    difficulty: "Medium",
    pattern: "Backtracking",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Backtracking",
  },
  {
    id: "abt-4",
    name: "Target Sum",
    url: "https://leetcode.com/problems/target-sum",
    difficulty: "Medium",
    pattern: "DP/Backtracking",
    companies: ["Google", "Meta"],
    frequency: "🔥🔥",
    category: "Backtracking",
  },
  {
    id: "abt-5",
    name: "Smallest Sufficient Team",
    url: "https://leetcode.com/problems/smallest-sufficient-team",
    difficulty: "Hard",
    pattern: "Bitmask DP",
    companies: ["Google"],
    frequency: "🔥",
    category: "Backtracking",
  },

  {
    id: "ahp-1",
    name: "Kth Largest Element in a Stream",
    url: "https://leetcode.com/problems/kth-largest-element-in-a-stream",
    difficulty: "Easy",
    pattern: "Min Heap",
    companies: ["Amazon", "Google", "Netflix"],
    frequency: "🔥🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "ahp-2",
    name: "Sliding Window Median",
    url: "https://leetcode.com/problems/sliding-window-median",
    difficulty: "Hard",
    pattern: "Two Heaps",
    companies: ["Bloomberg", "Google", "Stripe"],
    frequency: "🔥🔥",
    category: "Heap / Priority Queue",
  },

  {
    id: "ast-1",
    name: "Implement Queue using Stacks",
    url: "https://leetcode.com/problems/implement-queue-using-stacks",
    difficulty: "Easy",
    pattern: "Stack",
    companies: ["Amazon", "Apple"],
    frequency: "🔥🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "ast-2",
    name: "Implement Stack using Queues",
    url: "https://leetcode.com/problems/implement-stack-using-queues",
    difficulty: "Easy",
    pattern: "Queue",
    companies: ["Amazon", "Apple"],
    frequency: "🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "ast-3",
    name: "Min Stack",
    url: "https://leetcode.com/problems/min-stack",
    difficulty: "Medium",
    pattern: "Stack",
    companies: ["Amazon", "Microsoft", "Flipkart"],
    frequency: "🔥🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "ast-4",
    name: "Minimum Insertions to Balance a String",
    url: "https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string",
    difficulty: "Medium",
    pattern: "Stack",
    companies: ["Google"],
    frequency: "🔥",
    category: "Stack / Monotonic Stack",
  },

  {
    id: "all-1",
    name: "Linked List Cycle II",
    url: "https://leetcode.com/problems/linked-list-cycle-ii",
    difficulty: "Medium",
    pattern: "Floyd's Cycle",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Linked List",
  },
  {
    id: "all-2",
    name: "Middle of the Linked List",
    url: "https://leetcode.com/problems/middle-of-the-linked-list",
    difficulty: "Easy",
    pattern: "Fast/Slow",
    companies: ["Amazon"],
    frequency: "🔥🔥",
    category: "Linked List",
  },
  {
    id: "all-3",
    name: "Palindrome Linked List",
    url: "https://leetcode.com/problems/palindrome-linked-list",
    difficulty: "Easy",
    pattern: "Fast/Slow + Reverse",
    companies: ["Meta", "Amazon"],
    frequency: "🔥🔥",
    category: "Linked List",
  },

  {
    id: "aas-1",
    name: "Remove Duplicates from Sorted Array",
    url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Google", "Meta"],
    frequency: "🔥🔥",
    category: "Two Pointers",
  },
  {
    id: "aas-2",
    name: "Find All Numbers Disappeared in an Array",
    url: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array",
    difficulty: "Easy",
    pattern: "Cyclic Sort",
    companies: ["Google"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "aas-3",
    name: "Ransom Note",
    url: "https://leetcode.com/problems/ransom-note",
    difficulty: "Easy",
    pattern: "Hash Map",
    companies: ["Google"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "aas-4",
    name: "First Unique Character in a String",
    url: "https://leetcode.com/problems/first-unique-character-in-a-string",
    difficulty: "Easy",
    pattern: "Hash Map",
    companies: ["Amazon", "Adobe"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "aas-5",
    name: "Reverse String",
    url: "https://leetcode.com/problems/reverse-string",
    difficulty: "Easy",
    pattern: "Two Pointers",
    companies: ["Amazon"],
    frequency: "🔥",
    category: "Two Pointers",
  },
  {
    id: "aas-6",
    name: "4Sum",
    url: "https://leetcode.com/problems/4sum",
    difficulty: "Medium",
    pattern: "Two Pointers",
    companies: ["Facebook", "Adobe", "Microsoft"],
    frequency: "🔥",
    category: "Two Pointers",
  },
  {
    id: "aas-7",
    name: "Max Number of Vowels in Substring",
    url: "https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length",
    difficulty: "Medium",
    pattern: "Sliding Window",
    companies: ["Google"],
    frequency: "🔥",
    category: "Sliding Window",
  },
  {
    id: "aas-8",
    name: "Smallest Divisor Given Threshold",
    url: "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold",
    difficulty: "Medium",
    pattern: "Binary Search on Answer",
    companies: ["Google", "Uber", "Amazon"],
    frequency: "🔥",
    category: "Binary Search",
  },

  {
    id: "ahm-1",
    name: "Top K Frequent Words",
    url: "https://leetcode.com/problems/top-k-frequent-words",
    difficulty: "Medium",
    pattern: "Heap + HashMap",
    companies: ["Amazon", "Google"],
    frequency: "🔥🔥",
    category: "Hash Map / Set",
  },
  {
    id: "ahm-2",
    name: "Find First and Last Position of Element",
    url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array",
    difficulty: "Medium",
    pattern: "Binary Search",
    companies: ["Google", "Meta"],
    frequency: "🔥🔥",
    category: "Binary Search",
  },

  {
    id: "astr-1",
    name: "Longest Substring with At Most Two Distinct Characters",
    url: "https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters",
    difficulty: "Medium",
    pattern: "Sliding Window",
    companies: ["Google", "Atlassian"],
    frequency: "🔥🔥",
    category: "Sliding Window",
  },
  {
    id: "astr-2",
    name: "Reverse Words in a String",
    url: "https://leetcode.com/problems/reverse-words-in-a-string",
    difficulty: "Medium",
    pattern: "String",
    companies: ["Amazon", "Adobe"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "astr-3",
    name: "Zigzag Conversion",
    url: "https://leetcode.com/problems/zigzag-conversion",
    difficulty: "Medium",
    pattern: "String",
    companies: ["Google"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "astr-4",
    name: "Repeated Substring Pattern",
    url: "https://leetcode.com/problems/repeated-substring-pattern",
    difficulty: "Easy",
    pattern: "KMP/String",
    companies: ["Google"],
    frequency: "🔥",
    category: "Arrays & Strings",
  },
  {
    id: "astr-5",
    name: "Minimum Remove to Make Valid Parentheses",
    url: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses",
    difficulty: "Medium",
    pattern: "Stack/Two-Pass",
    companies: ["Meta", "Apple", "Microsoft"],
    frequency: "🔥🔥🔥",
    category: "Stack / Monotonic Stack",
  },

  {
    id: "atr-1",
    name: "Replace Words",
    url: "https://leetcode.com/problems/replace-words",
    difficulty: "Medium",
    pattern: "Trie",
    companies: ["Google", "Amazon"],
    frequency: "🔥",
    category: "Trie",
  },
  {
    id: "atr-2",
    name: "Longest Word in Dictionary",
    url: "https://leetcode.com/problems/longest-word-in-dictionary",
    difficulty: "Medium",
    pattern: "Trie",
    companies: ["Google"],
    frequency: "🔥",
    category: "Trie",
  },
  {
    id: "atr-3",
    name: "Map Sum Pairs",
    url: "https://leetcode.com/problems/map-sum-pairs",
    difficulty: "Medium",
    pattern: "Trie",
    companies: ["Google"],
    frequency: "🔥",
    category: "Trie",
  },

  {
    id: "seg-1",
    name: "Range Sum Query - Mutable",
    url: "https://leetcode.com/problems/range-sum-query-mutable",
    difficulty: "Medium",
    pattern: "Segment Tree/BIT",
    companies: ["Amazon", "Google"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "seg-2",
    name: "My Calendar III",
    url: "https://leetcode.com/problems/my-calendar-iii",
    difficulty: "Hard",
    pattern: "Segment Tree",
    companies: ["Google"],
    frequency: "🔥",
    category: "Design",
  },
  {
    id: "seg-3",
    name: "Count of Smaller Numbers After Self",
    url: "https://leetcode.com/problems/count-of-smaller-numbers-after-self",
    difficulty: "Hard",
    pattern: "Segment Tree/BIT",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "seg-4",
    name: "Shortest Subarray with Sum at Least K",
    url: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k",
    difficulty: "Hard",
    pattern: "Monotonic Deque",
    companies: ["Google"],
    frequency: "🔥",
    category: "Stack / Monotonic Stack",
  },

  {
    id: "amx-1",
    name: "Spiral Matrix II",
    url: "https://leetcode.com/problems/spiral-matrix-ii",
    difficulty: "Medium",
    pattern: "Simulation",
    companies: ["Google"],
    frequency: "🔥",
    category: "Matrix",
  },
  {
    id: "amx-2",
    name: "Transpose Matrix",
    url: "https://leetcode.com/problems/transpose-matrix",
    difficulty: "Easy",
    pattern: "Matrix",
    companies: ["Google"],
    frequency: "🔥",
    category: "Matrix",
  },
  {
    id: "amx-3",
    name: "Rectangle Area",
    url: "https://leetcode.com/problems/rectangle-area",
    difficulty: "Medium",
    pattern: "Geometry",
    companies: ["Google"],
    frequency: "🔥",
    category: "Matrix",
  },
  {
    id: "amx-4",
    name: "Valid Square",
    url: "https://leetcode.com/problems/valid-square",
    difficulty: "Medium",
    pattern: "Geometry",
    companies: ["Google"],
    frequency: "🔥",
    category: "Matrix",
  },
  {
    id: "amx-5",
    name: "Rotate Array",
    url: "https://leetcode.com/problems/rotate-array",
    difficulty: "Medium",
    pattern: "Array",
    companies: ["Google"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "amx-6",
    name: "Robot Bounded in Circle",
    url: "https://leetcode.com/problems/robot-bounded-in-circle",
    difficulty: "Medium",
    pattern: "Simulation",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Matrix",
  },

  {
    id: "ade-1",
    name: "Basic Calculator",
    url: "https://leetcode.com/problems/basic-calculator",
    difficulty: "Hard",
    pattern: "Stack",
    companies: ["Google", "Dropbox"],
    frequency: "🔥🔥",
    category: "Stack / Monotonic Stack",
  },
  {
    id: "ade-2",
    name: "Data Stream as Disjoint Intervals",
    url: "https://leetcode.com/problems/data-stream-as-disjoint-intervals",
    difficulty: "Hard",
    pattern: "TreeMap/BST",
    companies: ["Google"],
    frequency: "🔥",
    category: "Design",
  },
  {
    id: "ade-3",
    name: "Logger Rate Limiter",
    url: "https://leetcode.com/problems/logger-rate-limiter",
    difficulty: "Easy",
    pattern: "Hash Map",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "ade-4",
    name: "Design Snake Game",
    url: "https://leetcode.com/problems/design-snake-game",
    difficulty: "Medium",
    pattern: "Design/Deque",
    companies: ["Google", "Amazon"],
    frequency: "🔥",
    category: "Design",
  },
  {
    id: "ade-5",
    name: "Find Winner on a Tic Tac Toe Game",
    url: "https://leetcode.com/problems/find-winner-on-a-tic-tac-toe-game",
    difficulty: "Easy",
    pattern: "Simulation",
    companies: ["Google"],
    frequency: "🔥",
    category: "Design",
  },
  {
    id: "ade-6",
    name: "Design Twitter",
    url: "https://leetcode.com/problems/design-twitter",
    difficulty: "Medium",
    pattern: "Heap/Graph",
    companies: ["Google", "Meta"],
    frequency: "🔥🔥",
    category: "Design",
  },
  {
    id: "ade-7",
    name: "Rearrange String K Distance Apart",
    url: "https://leetcode.com/problems/rearrange-string-k-distance-apart",
    difficulty: "Hard",
    pattern: "Heap + Greedy",
    companies: ["Google", "Amazon"],
    frequency: "🔥🔥",
    category: "Heap / Priority Queue",
  },
  {
    id: "ade-8",
    name: "Smallest String With Swaps",
    url: "https://leetcode.com/problems/smallest-string-with-swaps",
    difficulty: "Medium",
    pattern: "Union-Find",
    companies: ["Google", "Dropbox"],
    frequency: "🔥",
    category: "Union-Find",
  },

  {
    id: "abit-1",
    name: "Single Number II",
    url: "https://leetcode.com/problems/single-number-ii",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    companies: ["Google"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "abit-2",
    name: "Single Number III",
    url: "https://leetcode.com/problems/single-number-iii",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    companies: ["Google", "Meta"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "abit-3",
    name: "Bitwise AND of Numbers Range",
    url: "https://leetcode.com/problems/bitwise-and-of-numbers-range",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    companies: ["Google"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "abit-4",
    name: "Maximum XOR of Two Numbers",
    url: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array",
    difficulty: "Medium",
    pattern: "Binary Trie",
    companies: ["Google", "Nvidia", "Qualcomm"],
    frequency: "🔥🔥",
    category: "Math / Bit Manipulation",
  },

  {
    id: "amt-1",
    name: "Max Points on a Line",
    url: "https://leetcode.com/problems/max-points-on-a-line",
    difficulty: "Hard",
    pattern: "Math/GCD",
    companies: ["Google", "Meta"],
    frequency: "🔥🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "amt-2",
    name: "Count Primes",
    url: "https://leetcode.com/problems/count-primes",
    difficulty: "Medium",
    pattern: "Sieve",
    companies: ["Google"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "amt-3",
    name: "Super Pow",
    url: "https://leetcode.com/problems/super-pow",
    difficulty: "Medium",
    pattern: "Binary Exponentiation",
    companies: ["Google"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "amt-4",
    name: "Pascal's Triangle",
    url: "https://leetcode.com/problems/pascals-triangle",
    difficulty: "Easy",
    pattern: "Math/DP",
    companies: ["Google"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },
  {
    id: "amt-5",
    name: "Pascal's Triangle II",
    url: "https://leetcode.com/problems/pascals-triangle-ii",
    difficulty: "Easy",
    pattern: "Math/DP",
    companies: ["Google"],
    frequency: "🔥",
    category: "Math / Bit Manipulation",
  },

  {
    id: "agy-1",
    name: "Jump Game IV",
    url: "https://leetcode.com/problems/jump-game-iv",
    difficulty: "Hard",
    pattern: "BFS",
    companies: ["Google", "Amazon"],
    frequency: "🔥",
    category: "Graphs",
  },
  {
    id: "agy-2",
    name: "Maximum Sum Circular Subarray",
    url: "https://leetcode.com/problems/maximum-sum-circular-subarray",
    difficulty: "Medium",
    pattern: "Kadane's Variant",
    companies: ["Amazon"],
    frequency: "🔥🔥",
    category: "Arrays & Strings",
  },
  {
    id: "agy-3",
    name: "Online Stock Span",
    url: "https://leetcode.com/problems/online-stock-span",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    companies: ["Amazon", "Google"],
    frequency: "🔥🔥",
    category: "Stack / Monotonic Stack",
  },
];

// Map category names to pattern IDs
export const categoryToPatternId: Record<string, string> = {
  "Arrays & Strings": "arrays-strings",
  "Two Pointers": "two-pointers",
  "Sliding Window": "sliding-window",
  "Prefix Sum": "prefix-sum",
  "Hash Map / Set": "hash-map",
  "Binary Search": "binary-search",
  "Stack / Monotonic Stack": "stack",
  "Linked List": "linked-list",
  Trees: "trees",
  Graphs: "graphs",
  "Heap / Priority Queue": "heap",
  "Dynamic Programming": "dynamic-programming",
  Backtracking: "backtracking",
  Intervals: "intervals",
  Trie: "trie",
  "Union-Find": "union-find",
  Design: "design",
  Matrix: "matrix",
  Greedy: "greedy",
  "Math / Bit Manipulation": "math-bit",
  "Divide and Conquer": "divide-conquer",
  Concurrency: "concurrency",
};

export function getCategories(): string[] {
  return [...new Set(questions.map((q) => q.category))];
}

export function getCompanies(): string[] {
  const companies = new Set<string>();
  questions.forEach((q) => q.companies.forEach((c) => companies.add(c)));
  return [...companies].sort();
}

export function getQuestionsByCategory(category: string): Question[] {
  return questions.filter((q) => q.category === category);
}
